// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/catalog/v1/catalog.proto

package catalogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetProductReq 获取商品请求
type GetProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 商品ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductReq) Reset() {
	*x = GetProductReq{}
	mi := &file_api_catalog_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductReq) ProtoMessage() {}

func (x *GetProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductReq.ProtoReflect.Descriptor instead.
func (*GetProductReq) Descriptor() ([]byte, []int) {
	return file_api_catalog_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetProductResp 获取商品响应
type GetProductResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                // 商品ID
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                             // 商品名称
	ShortDesc      string                 `protobuf:"bytes,3,opt,name=short_desc,json=shortDesc,proto3" json:"short_desc,omitempty"`                  // 商品简介
	FullDesc       string                 `protobuf:"bytes,4,opt,name=full_desc,json=fullDesc,proto3" json:"full_desc,omitempty"`                     // 商品详细描述
	Sku            string                 `protobuf:"bytes,5,opt,name=sku,proto3" json:"sku,omitempty"`                                               // SKU编码
	Price          float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`                                         // 售价
	OldPrice       float64                `protobuf:"fixed64,7,opt,name=old_price,json=oldPrice,proto3" json:"old_price,omitempty"`                   // 原价
	Cost           float64                `protobuf:"fixed64,8,opt,name=cost,proto3" json:"cost,omitempty"`                                           // 成本价
	Stock          int32                  `protobuf:"varint,9,opt,name=stock,proto3" json:"stock,omitempty"`                                          // 库存数量
	CategoryId     uint32                 `protobuf:"varint,10,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`             // 分类ID
	ManufacturerId uint32                 `protobuf:"varint,11,opt,name=manufacturer_id,json=manufacturerId,proto3" json:"manufacturer_id,omitempty"` // 制造商ID
	IsPublished    bool                   `protobuf:"varint,12,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`          // 是否上架
	CreatedAt      int64                  `protobuf:"varint,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                // 创建时间
	UpdatedAt      int64                  `protobuf:"varint,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                // 更新时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetProductResp) Reset() {
	*x = GetProductResp{}
	mi := &file_api_catalog_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResp) ProtoMessage() {}

func (x *GetProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResp.ProtoReflect.Descriptor instead.
func (*GetProductResp) Descriptor() ([]byte, []int) {
	return file_api_catalog_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductResp) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetProductResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProductResp) GetShortDesc() string {
	if x != nil {
		return x.ShortDesc
	}
	return ""
}

func (x *GetProductResp) GetFullDesc() string {
	if x != nil {
		return x.FullDesc
	}
	return ""
}

func (x *GetProductResp) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *GetProductResp) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetProductResp) GetOldPrice() float64 {
	if x != nil {
		return x.OldPrice
	}
	return 0
}

func (x *GetProductResp) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *GetProductResp) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *GetProductResp) GetCategoryId() uint32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *GetProductResp) GetManufacturerId() uint32 {
	if x != nil {
		return x.ManufacturerId
	}
	return 0
}

func (x *GetProductResp) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

func (x *GetProductResp) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetProductResp) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// ListProductsReq 获取商品列表请求
type ListProductsReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Page           int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                                           // 页码
	Size           int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`                                           // 每页条数
	CategoryId     uint32                 `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`             // 分类ID（可选）
	ManufacturerId uint32                 `protobuf:"varint,4,opt,name=manufacturer_id,json=manufacturerId,proto3" json:"manufacturer_id,omitempty"` // 制造商ID（可选）
	Keyword        string                 `protobuf:"bytes,5,opt,name=keyword,proto3" json:"keyword,omitempty"`                                      // 搜索关键词（可选）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListProductsReq) Reset() {
	*x = ListProductsReq{}
	mi := &file_api_catalog_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsReq) ProtoMessage() {}

func (x *ListProductsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsReq.ProtoReflect.Descriptor instead.
func (*ListProductsReq) Descriptor() ([]byte, []int) {
	return file_api_catalog_v1_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *ListProductsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListProductsReq) GetCategoryId() uint32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ListProductsReq) GetManufacturerId() uint32 {
	if x != nil {
		return x.ManufacturerId
	}
	return 0
}

func (x *ListProductsReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

// ListProductsResp 获取商品列表响应
type ListProductsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*GetProductResp      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`  // 商品列表
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResp) Reset() {
	*x = ListProductsResp{}
	mi := &file_api_catalog_v1_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResp) ProtoMessage() {}

func (x *ListProductsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_v1_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResp.ProtoReflect.Descriptor instead.
func (*ListProductsResp) Descriptor() ([]byte, []int) {
	return file_api_catalog_v1_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *ListProductsResp) GetItems() []*GetProductResp {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListProductsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// GetCategoryReq 获取分类请求
type GetCategoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 分类ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryReq) Reset() {
	*x = GetCategoryReq{}
	mi := &file_api_catalog_v1_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryReq) ProtoMessage() {}

func (x *GetCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_v1_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryReq.ProtoReflect.Descriptor instead.
func (*GetCategoryReq) Descriptor() ([]byte, []int) {
	return file_api_catalog_v1_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *GetCategoryReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetCategoryResp 获取分类响应
type GetCategoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                      // 分类ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                   // 分类名称
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                     // 分类描述
	ParentId      uint32                 `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`          // 父分类ID
	SortOrder     int32                  `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`       // 排序权重
	IsPublished   bool                   `protobuf:"varint,6,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"` // 是否启用
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`       // 创建时间
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`       // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryResp) Reset() {
	*x = GetCategoryResp{}
	mi := &file_api_catalog_v1_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryResp) ProtoMessage() {}

func (x *GetCategoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_v1_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryResp.ProtoReflect.Descriptor instead.
func (*GetCategoryResp) Descriptor() ([]byte, []int) {
	return file_api_catalog_v1_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *GetCategoryResp) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCategoryResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCategoryResp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetCategoryResp) GetParentId() uint32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *GetCategoryResp) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *GetCategoryResp) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

func (x *GetCategoryResp) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetCategoryResp) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// ListCountriesReq 获取国家列表请求
type ListCountriesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"` // 页码
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"` // 每页条数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCountriesReq) Reset() {
	*x = ListCountriesReq{}
	mi := &file_api_catalog_v1_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCountriesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCountriesReq) ProtoMessage() {}

func (x *ListCountriesReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_v1_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCountriesReq.ProtoReflect.Descriptor instead.
func (*ListCountriesReq) Descriptor() ([]byte, []int) {
	return file_api_catalog_v1_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *ListCountriesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCountriesReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// ListCountriesResp 获取国家列表响应
type ListCountriesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CountryItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`  // 国家列表
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCountriesResp) Reset() {
	*x = ListCountriesResp{}
	mi := &file_api_catalog_v1_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCountriesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCountriesResp) ProtoMessage() {}

func (x *ListCountriesResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_v1_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCountriesResp.ProtoReflect.Descriptor instead.
func (*ListCountriesResp) Descriptor() ([]byte, []int) {
	return file_api_catalog_v1_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *ListCountriesResp) GetItems() []*CountryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListCountriesResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// CountryItem 国家条目
type CountryItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                     // 国家ID
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                  // 国家名称
	IsoCode2         string                 `protobuf:"bytes,3,opt,name=iso_code2,json=isoCode2,proto3" json:"iso_code2,omitempty"`                          // ISO 2字母代码
	IsoCode3         string                 `protobuf:"bytes,4,opt,name=iso_code3,json=isoCode3,proto3" json:"iso_code3,omitempty"`                          // ISO 3字母代码
	AddressFormat    string                 `protobuf:"bytes,5,opt,name=address_format,json=addressFormat,proto3" json:"address_format,omitempty"`           // 地址格式
	PostcodeRequired bool                   `protobuf:"varint,6,opt,name=postcode_required,json=postcodeRequired,proto3" json:"postcode_required,omitempty"` // 是否必填邮编
	CreatedAt        string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                       // 创建时间
	UpdatedAt        string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                       // 更新时间
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CountryItem) Reset() {
	*x = CountryItem{}
	mi := &file_api_catalog_v1_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountryItem) ProtoMessage() {}

func (x *CountryItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_v1_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountryItem.ProtoReflect.Descriptor instead.
func (*CountryItem) Descriptor() ([]byte, []int) {
	return file_api_catalog_v1_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *CountryItem) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CountryItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CountryItem) GetIsoCode2() string {
	if x != nil {
		return x.IsoCode2
	}
	return ""
}

func (x *CountryItem) GetIsoCode3() string {
	if x != nil {
		return x.IsoCode3
	}
	return ""
}

func (x *CountryItem) GetAddressFormat() string {
	if x != nil {
		return x.AddressFormat
	}
	return ""
}

func (x *CountryItem) GetPostcodeRequired() bool {
	if x != nil {
		return x.PostcodeRequired
	}
	return false
}

func (x *CountryItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CountryItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_api_catalog_v1_catalog_proto protoreflect.FileDescriptor

const file_api_catalog_v1_catalog_proto_rawDesc = "" +
	"\n" +
	"\x1capi/catalog/v1/catalog.proto\x12\n" +
	"catalog.v1\"\x1f\n" +
	"\rGetProductReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x8a\x03\n" +
	"\x0eGetProductResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"short_desc\x18\x03 \x01(\tR\tshortDesc\x12\x1b\n" +
	"\tfull_desc\x18\x04 \x01(\tR\bfullDesc\x12\x10\n" +
	"\x03sku\x18\x05 \x01(\tR\x03sku\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x1b\n" +
	"\told_price\x18\a \x01(\x01R\boldPrice\x12\x12\n" +
	"\x04cost\x18\b \x01(\x01R\x04cost\x12\x14\n" +
	"\x05stock\x18\t \x01(\x05R\x05stock\x12\x1f\n" +
	"\vcategory_id\x18\n" +
	" \x01(\rR\n" +
	"categoryId\x12'\n" +
	"\x0fmanufacturer_id\x18\v \x01(\rR\x0emanufacturerId\x12!\n" +
	"\fis_published\x18\f \x01(\bR\visPublished\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\x03R\tupdatedAt\"\x9d\x01\n" +
	"\x0fListProductsReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\rR\n" +
	"categoryId\x12'\n" +
	"\x0fmanufacturer_id\x18\x04 \x01(\rR\x0emanufacturerId\x12\x18\n" +
	"\akeyword\x18\x05 \x01(\tR\akeyword\"Z\n" +
	"\x10ListProductsResp\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.catalog.v1.GetProductRespR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\" \n" +
	"\x0eGetCategoryReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\xf4\x01\n" +
	"\x0fGetCategoryResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\rR\bparentId\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x05R\tsortOrder\x12!\n" +
	"\fis_published\x18\x06 \x01(\bR\visPublished\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\":\n" +
	"\x10ListCountriesReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"X\n" +
	"\x11ListCountriesResp\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.catalog.v1.CountryItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xfd\x01\n" +
	"\vCountryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tiso_code2\x18\x03 \x01(\tR\bisoCode2\x12\x1b\n" +
	"\tiso_code3\x18\x04 \x01(\tR\bisoCode3\x12%\n" +
	"\x0eaddress_format\x18\x05 \x01(\tR\raddressFormat\x12+\n" +
	"\x11postcode_required\x18\x06 \x01(\bR\x10postcodeRequired\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt2\xb2\x02\n" +
	"\n" +
	"CatalogRPC\x12C\n" +
	"\n" +
	"GetProduct\x12\x19.catalog.v1.GetProductReq\x1a\x1a.catalog.v1.GetProductResp\x12I\n" +
	"\fListProducts\x12\x1b.catalog.v1.ListProductsReq\x1a\x1c.catalog.v1.ListProductsResp\x12F\n" +
	"\vGetCategory\x12\x1a.catalog.v1.GetCategoryReq\x1a\x1b.catalog.v1.GetCategoryResp\x12L\n" +
	"\rListCountries\x12\x1c.catalog.v1.ListCountriesReq\x1a\x1d.catalog.v1.ListCountriesRespB:Z8nop-go/services/catalog-service/api/catalog/v1;catalogv1b\x06proto3"

var (
	file_api_catalog_v1_catalog_proto_rawDescOnce sync.Once
	file_api_catalog_v1_catalog_proto_rawDescData []byte
)

func file_api_catalog_v1_catalog_proto_rawDescGZIP() []byte {
	file_api_catalog_v1_catalog_proto_rawDescOnce.Do(func() {
		file_api_catalog_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_catalog_v1_catalog_proto_rawDesc), len(file_api_catalog_v1_catalog_proto_rawDesc)))
	})
	return file_api_catalog_v1_catalog_proto_rawDescData
}

var file_api_catalog_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_catalog_v1_catalog_proto_goTypes = []any{
	(*GetProductReq)(nil),     // 0: catalog.v1.GetProductReq
	(*GetProductResp)(nil),    // 1: catalog.v1.GetProductResp
	(*ListProductsReq)(nil),   // 2: catalog.v1.ListProductsReq
	(*ListProductsResp)(nil),  // 3: catalog.v1.ListProductsResp
	(*GetCategoryReq)(nil),    // 4: catalog.v1.GetCategoryReq
	(*GetCategoryResp)(nil),   // 5: catalog.v1.GetCategoryResp
	(*ListCountriesReq)(nil),  // 6: catalog.v1.ListCountriesReq
	(*ListCountriesResp)(nil), // 7: catalog.v1.ListCountriesResp
	(*CountryItem)(nil),       // 8: catalog.v1.CountryItem
}
var file_api_catalog_v1_catalog_proto_depIdxs = []int32{
	1, // 0: catalog.v1.ListProductsResp.items:type_name -> catalog.v1.GetProductResp
	8, // 1: catalog.v1.ListCountriesResp.items:type_name -> catalog.v1.CountryItem
	0, // 2: catalog.v1.CatalogRPC.GetProduct:input_type -> catalog.v1.GetProductReq
	2, // 3: catalog.v1.CatalogRPC.ListProducts:input_type -> catalog.v1.ListProductsReq
	4, // 4: catalog.v1.CatalogRPC.GetCategory:input_type -> catalog.v1.GetCategoryReq
	6, // 5: catalog.v1.CatalogRPC.ListCountries:input_type -> catalog.v1.ListCountriesReq
	1, // 6: catalog.v1.CatalogRPC.GetProduct:output_type -> catalog.v1.GetProductResp
	3, // 7: catalog.v1.CatalogRPC.ListProducts:output_type -> catalog.v1.ListProductsResp
	5, // 8: catalog.v1.CatalogRPC.GetCategory:output_type -> catalog.v1.GetCategoryResp
	7, // 9: catalog.v1.CatalogRPC.ListCountries:output_type -> catalog.v1.ListCountriesResp
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_catalog_v1_catalog_proto_init() }
func file_api_catalog_v1_catalog_proto_init() {
	if File_api_catalog_v1_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_catalog_v1_catalog_proto_rawDesc), len(file_api_catalog_v1_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_catalog_v1_catalog_proto_goTypes,
		DependencyIndexes: file_api_catalog_v1_catalog_proto_depIdxs,
		MessageInfos:      file_api_catalog_v1_catalog_proto_msgTypes,
	}.Build()
	File_api_catalog_v1_catalog_proto = out.File
	file_api_catalog_v1_catalog_proto_goTypes = nil
	file_api_catalog_v1_catalog_proto_depIdxs = nil
}
