// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/catalog/v1/catalog.proto

package catalogv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogRPC_GetProduct_FullMethodName    = "/catalog.v1.CatalogRPC/GetProduct"
	CatalogRPC_ListProducts_FullMethodName  = "/catalog.v1.CatalogRPC/ListProducts"
	CatalogRPC_GetCategory_FullMethodName   = "/catalog.v1.CatalogRPC/GetCategory"
	CatalogRPC_ListCountries_FullMethodName = "/catalog.v1.CatalogRPC/ListCountries"
)

// CatalogRPCClient is the client API for CatalogRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CatalogRPC 商品服务 gRPC 接口 —— 定义其他服务（trade-service、content-service）需要跨服务调用的方法。
type CatalogRPCClient interface {
	// GetProduct 根据 ID 获取商品信息（trade 结算时获取商品价格、content 商品展示时获取商品详情）
	GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*GetProductResp, error)
	// ListProducts 获取商品列表（trade 批量验证库存、content 商品展示列表）
	ListProducts(ctx context.Context, in *ListProductsReq, opts ...grpc.CallOption) (*ListProductsResp, error)
	// GetCategory 根据 ID 获取分类信息（content 商品分类展示）
	GetCategory(ctx context.Context, in *GetCategoryReq, opts ...grpc.CallOption) (*GetCategoryResp, error)
	// ListCountries 获取国家列表（trade 结算时选择配送国家）
	ListCountries(ctx context.Context, in *ListCountriesReq, opts ...grpc.CallOption) (*ListCountriesResp, error)
}

type catalogRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogRPCClient(cc grpc.ClientConnInterface) CatalogRPCClient {
	return &catalogRPCClient{cc}
}

func (c *catalogRPCClient) GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*GetProductResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductResp)
	err := c.cc.Invoke(ctx, CatalogRPC_GetProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogRPCClient) ListProducts(ctx context.Context, in *ListProductsReq, opts ...grpc.CallOption) (*ListProductsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductsResp)
	err := c.cc.Invoke(ctx, CatalogRPC_ListProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogRPCClient) GetCategory(ctx context.Context, in *GetCategoryReq, opts ...grpc.CallOption) (*GetCategoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoryResp)
	err := c.cc.Invoke(ctx, CatalogRPC_GetCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogRPCClient) ListCountries(ctx context.Context, in *ListCountriesReq, opts ...grpc.CallOption) (*ListCountriesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCountriesResp)
	err := c.cc.Invoke(ctx, CatalogRPC_ListCountries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogRPCServer is the server API for CatalogRPC service.
// All implementations must embed UnimplementedCatalogRPCServer
// for forward compatibility.
//
// CatalogRPC 商品服务 gRPC 接口 —— 定义其他服务（trade-service、content-service）需要跨服务调用的方法。
type CatalogRPCServer interface {
	// GetProduct 根据 ID 获取商品信息（trade 结算时获取商品价格、content 商品展示时获取商品详情）
	GetProduct(context.Context, *GetProductReq) (*GetProductResp, error)
	// ListProducts 获取商品列表（trade 批量验证库存、content 商品展示列表）
	ListProducts(context.Context, *ListProductsReq) (*ListProductsResp, error)
	// GetCategory 根据 ID 获取分类信息（content 商品分类展示）
	GetCategory(context.Context, *GetCategoryReq) (*GetCategoryResp, error)
	// ListCountries 获取国家列表（trade 结算时选择配送国家）
	ListCountries(context.Context, *ListCountriesReq) (*ListCountriesResp, error)
	mustEmbedUnimplementedCatalogRPCServer()
}

// UnimplementedCatalogRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogRPCServer struct{}

func (UnimplementedCatalogRPCServer) GetProduct(context.Context, *GetProductReq) (*GetProductResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedCatalogRPCServer) ListProducts(context.Context, *ListProductsReq) (*ListProductsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProducts not implemented")
}
func (UnimplementedCatalogRPCServer) GetCategory(context.Context, *GetCategoryReq) (*GetCategoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategory not implemented")
}
func (UnimplementedCatalogRPCServer) ListCountries(context.Context, *ListCountriesReq) (*ListCountriesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCountries not implemented")
}
func (UnimplementedCatalogRPCServer) mustEmbedUnimplementedCatalogRPCServer() {}
func (UnimplementedCatalogRPCServer) testEmbeddedByValue()                    {}

// UnsafeCatalogRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogRPCServer will
// result in compilation errors.
type UnsafeCatalogRPCServer interface {
	mustEmbedUnimplementedCatalogRPCServer()
}

func RegisterCatalogRPCServer(s grpc.ServiceRegistrar, srv CatalogRPCServer) {
	// If the following call panics, it indicates UnimplementedCatalogRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogRPC_ServiceDesc, srv)
}

func _CatalogRPC_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogRPCServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogRPC_GetProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogRPCServer).GetProduct(ctx, req.(*GetProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogRPC_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogRPCServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogRPC_ListProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogRPCServer).ListProducts(ctx, req.(*ListProductsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogRPC_GetCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogRPCServer).GetCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogRPC_GetCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogRPCServer).GetCategory(ctx, req.(*GetCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogRPC_ListCountries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCountriesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogRPCServer).ListCountries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogRPC_ListCountries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogRPCServer).ListCountries(ctx, req.(*ListCountriesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogRPC_ServiceDesc is the grpc.ServiceDesc for CatalogRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalog.v1.CatalogRPC",
	HandlerType: (*CatalogRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProduct",
			Handler:    _CatalogRPC_GetProduct_Handler,
		},
		{
			MethodName: "ListProducts",
			Handler:    _CatalogRPC_ListProducts_Handler,
		},
		{
			MethodName: "GetCategory",
			Handler:    _CatalogRPC_GetCategory_Handler,
		},
		{
			MethodName: "ListCountries",
			Handler:    _CatalogRPC_ListCountries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/catalog/v1/catalog.proto",
}
