//go:build !wireinject

// Code generated by Wire. DO NOT EDIT.

package main

import (
	"github.com/ngq/gorp"
	"gorm.io/gorm"
	"grpc-demo/services/product/internal/service"
)

func wireProductServices(db *gorm.DB, publisher gorp.MessagePublisher, subscriber gorp.MessageSubscriber) (*service.Services, error) {
	services := service.NewServices(db, publisher, subscriber)
	return services, nil
}
