apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grpc-demo-prod

resources:
  - ../../base
  - hpa.yaml
  - ingress.yaml

images:
  - name: your-registry/grpc-demo-user-service
    newName: your-registry/grpc-demo-user-service
    newTag: v1.0.0
  - name: your-registry/grpc-demo-order-service
    newName: your-registry/grpc-demo-order-service
    newTag: v1.0.0
  - name: your-registry/grpc-demo-product-service
    newName: your-registry/grpc-demo-product-service
    newTag: v1.0.0

patches:
  - path: deployment-patch.yaml
