// Code generated by Claude Code. DO NOT EDIT.

package main

import (
	"nop-go/services/price-service/internal/biz"
	"nop-go/services/price-service/internal/data"
	"nop-go/services/price-service/internal/service"

	"gorm.io/gorm"
)

func wirePriceService(db *gorm.DB) (*service.PriceService, error) {
	taxRepo := data.NewTaxRateRepository(db)
	discountRepo := data.NewDiscountRepository(db)
	priceRepo := data.NewProductPriceRepository(db)
	taxUC := biz.NewTaxUseCase(taxRepo)
	discountUC := biz.NewDiscountUseCase(discountRepo)
	priceUC := biz.NewPriceUseCase(priceRepo, taxRepo, discountRepo)
	priceService := service.NewPriceService(priceUC, taxUC, discountUC)
	return priceService, nil
}
