// Code generated by Claude Code. DO NOT EDIT.

package main

import (
	"nop-go/services/cms-service/internal/biz"
	"nop-go/services/cms-service/internal/data"
	"nop-go/services/cms-service/internal/service"

	"gorm.io/gorm"
)

// wireCMSService 使用接近 multi-flat-wire 的方式收口 cms-service 的装配链。
func wireCMSService(db *gorm.DB) (*service.CMSService, error) {
	blogRepo := data.NewBlogPostRepository(db)
	blogCategoryRepo := data.NewBlogCategoryRepository(db)
	newsRepo := data.NewNewsRepository(db)
	topicRepo := data.NewTopicRepository(db)
	forumRepo := data.NewForumRepository(db)
	menuRepo := data.NewMenuRepository(db)
	menuItemRepo := data.NewMenuItemRepository(db)
	pollRepo := data.NewPollRepository(db)
	pollAnswerRepo := data.NewPollAnswerRepository(db)
	pollRecordRepo := data.NewPollVotingRecordRepository(db)
	htmlRepo := data.NewHtmlBodyRepository(db)

	blogUC := biz.NewBlogUseCase(blogRepo, blogCategoryRepo)
	newsUC := biz.NewNewsUseCase(newsRepo)
	topicUC := biz.NewTopicUseCase(topicRepo)
	forumUC := biz.NewForumUseCase(forumRepo)
	menuUC := biz.NewMenuUseCase(menuRepo, menuItemRepo)
	pollUC := biz.NewPollUseCase(pollRepo, pollAnswerRepo, pollRecordRepo)
	htmlUC := biz.NewHtmlBodyUseCase(htmlRepo)

	cmsService := service.NewCMSService(blogUC, newsUC, topicUC, forumUC, menuUC, pollUC, htmlUC)
	return cmsService, nil
}
