// Code generated by Claude Code. DO NOT EDIT.

package main

import (
	"nop-go/services/theme-service/internal/biz"
	"nop-go/services/theme-service/internal/data"
	"nop-go/services/theme-service/internal/service"
	"nop-go/shared/bootstrap"

	"github.com/ngq/gorp/framework/contract"
	"gorm.io/gorm"
)

func themeConfigFromRuntime(rt *bootstrap.HTTPServiceRuntime) biz.ThemeConfig {
	config := biz.ThemeConfig{
		ThemesDir:          rt.Config.GetString("theme.themes_dir"),
		DefaultTheme:       rt.Config.GetString("theme.default_theme"),
		AllowUserSelection: rt.Config.GetBool("theme.allow_user_selection"),
	}
	if config.ThemesDir == "" {
		config.ThemesDir = "./themes"
	}
	if config.DefaultTheme == "" {
		config.DefaultTheme = "default"
	}
	return config
}

func wireThemeService(db *gorm.DB, jwtSvc contract.JWTService, config biz.ThemeConfig) (*service.ThemeService, error) {
	themeRepo := data.NewThemeRepository(db)
	variableRepo := data.NewThemeVariableRepository(db)
	configRepo := data.NewThemeConfigurationRepository(db)
	customerRepo := data.NewCustomerThemeSettingRepository(db)
	fileRepo := data.NewThemeFileRepository(db)
	themeUC := biz.NewThemeUseCase(themeRepo, variableRepo, configRepo, customerRepo, fileRepo, config)
	configUC := biz.NewThemeConfigurationUseCase(configRepo, themeRepo)
	customerUC := biz.NewCustomerThemeUseCase(customerRepo, themeRepo)
	fileUC := biz.NewThemeFileUseCase(fileRepo, themeRepo)
	themeService := service.NewThemeService(themeUC, configUC, customerUC, fileUC, jwtSvc)
	return themeService, nil
}
