package model

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	datacontract "github.com/ngq/gorp/framework/contract/data"

	"github.com/spf13/cobra"
)

var (
	modelGenTable string
	modelGenOut   string
)

// modelGenCmd 根据数据库表结构生成一个基础 Go struct。
//
// 中文说明：
// - 它主要面向"先快速拿到模型骨架"这一需求。
// - 当前生成结果比较克制：只输出字段、db/json tag，不自动生成完整 CRUD。
// - 如果要进一步生成 service/http 层，可使用 `gorp model api`。
var modelGenCmd = &cobra.Command{
	Use:   "gen",
	Short: "Generate a simple struct model from DB table",
	RunE: func(cmd *cobra.Command, args []string) error {
		_, c, err := bootstrap()
		if err != nil {
			return err
		}
		insAny, err := c.Make(datacontract.DBInspectorKey)
		if err != nil {
			return err
		}
		ins := insAny.(datacontract.DBInspector)

		if modelGenTable == "" {
			return fmt.Errorf("--table is required")
		}
		cols, err := ins.Columns(cmd.Context(), modelGenTable)
		if err != nil {
			return err
		}

		outDir := modelGenOut
		if outDir == "" {
			outDir = filepath.Join("app", "model", "gen")
		}
		if err := os.MkdirAll(outDir, 0o755); err != nil {
			return err
		}

		data := struct {
			Table  string
			Name   string
			Cols   []datacontract.Column
			Driver string
		}{
			Table:  modelGenTable,
			Name:   toGoName(modelGenTable),
			Cols:   cols,
			Driver: driverFromInspector(ins),
		}

		file := filepath.Join(outDir, strings.ToLower(data.Name)+".go")
		f, err := os.Create(file)
		if err != nil {
			return err
		}
		defer f.Close()

		tpl := template.Must(template.New("model").Funcs(template.FuncMap{
			"dbTypeToGo": dbTypeToGo,
			"toGoName":    toGoName,
		}).Parse(modelTpl))
		if err := tpl.Execute(f, data); err != nil {
			return err
		}
		fmt.Fprintf(cmd.OutOrStdout(), "generated: %s\n", file)
		return nil
	},
}

func init() {
	modelGenCmd.Flags().StringVar(&modelGenTable, "table", "", "table name")
	modelGenCmd.Flags().StringVar(&modelGenOut, "out", "", "output directory")
}

const modelTpl = `package gen

// Code generated by gorp model gen; DO NOT EDIT.
//
// 类型映射说明：
// - decimal/numeric → float64（精度要求高的场景建议用 shopspring/decimal）
// - json/jsonb → string（需要强类型可自行替换为 map[string]any 或自定义类型）
// - uuid → string（需要强类型可自行替换为 github.com/google/uuid）
// - 时间字段已映射为 time.Time

type {{.Name}} struct {
{{- range .Cols }}
	{{- if .Comment }}// {{ .Comment }}
	{{ toGoName .Name }} {{ dbTypeToGo $.Driver .Type }} ` + "`gorm:\"column:{{.Name}}\" db:\"{{.Name}}\" json:\"{{.Name}}\"`" + `
{{- else }}// {{ toGoName .Name }}
	{{ toGoName .Name }} {{ dbTypeToGo $.Driver .Type }} ` + "`gorm:\"column:{{.Name}}\" db:\"{{.Name}}\" json:\"{{.Name}}\"`" + `
{{- end }}
{{- end }}
}
`

// DriverGetter 提供数据库驱动名，用于类型映射。
// DBInspector 实现此接口，Columns 返回值中包含 Driver 字段。
type DriverGetter interface {
	Driver() string
}

func driverFromInspector(ins any) string {
	if dg, ok := ins.(DriverGetter); ok {
		return dg.Driver()
	}
	return "sqlite"
}

func toGoName(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-'
	})
	for i := range parts {
		if len(parts[i]) == 0 {
			continue
		}
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return strings.Join(parts, "")
}

// dbTypeToGo 根据数据库驱动和列类型返回对应的 Go 类型。
// 支持 sqlite、mysql、postgres 三种驱动。
// 对于无法识别的类型，返回 string 作为安全默认值。
func dbTypeToGo(driver, colType string) string {
	switch driver {
	case "sqlite", "sqlite3":
		return sqliteTypeToGo(colType)
	case "mysql":
		return mysqlTypeToGo(colType)
	case "pgx", "postgres":
		return pgTypeToGo(colType)
	default:
		return sqliteTypeToGo(colType)
	}
}

// sqliteTypeToGo 将 SQLite 列类型映射为 Go 类型。
func sqliteTypeToGo(t string) string {
	t = strings.ToUpper(t)
	switch {
	case strings.Contains(t, "INT"):
		return "int64"
	case strings.Contains(t, "CHAR"), strings.Contains(t, "TEXT"), strings.Contains(t, "CLOB"):
		return "string"
	case strings.Contains(t, "BLOB"):
		return "[]byte"
	case strings.Contains(t, "REAL"), strings.Contains(t, "FLOA"), strings.Contains(t, "DOUB"):
		return "float64"
	case strings.Contains(t, "BOOL"):
		return "bool"
	default:
		return "string"
	}
}

// mysqlTypeToGo 将 MySQL 列类型映射为 Go 类型。
// 处理带参数的完整类型名，如 bigint(20) unsigned、decimal(10,2)。
func mysqlTypeToGo(colType string) string {
	t := strings.ToUpper(colType)

	// 先处理带参数的完整类型名
	// 去掉括号及内部内容，只保留类型名主体
	baseType := t
	if idx := strings.Index(t, "("); idx >= 0 {
		baseType = strings.TrimSpace(t[:idx])
	}

	// 判断是否带 unsigned/signed 修饰符（跟在类型后面）
	hasUnsigned := strings.Contains(t, "UNSIGNED")

	switch baseType {
	case "INT", "INTEGER":
		if hasUnsigned {
			return "uint64"
		}
		return "int64"
	case "BIGINT":
		if hasUnsigned {
			return "uint64"
		}
		return "int64"
	case "MEDIUMINT":
		if hasUnsigned {
			return "uint64"
		}
		return "int64"
	case "SMALLINT", "YEAR":
		if hasUnsigned {
			return "uint64"
		}
		return "int64"
	case "TINYINT":
		if hasUnsigned {
			return "uint64"
		}
		return "int64"
	case "FLOAT":
		return "float64"
	case "DOUBLE", "DOUBLE PRECISION":
		return "float64"
	case "DECIMAL", "DEC", "NUMERIC":
		// decimal/numeric 通常用于金额，建议用 string 或 float64
		// 这里用 float64 作为默认，对于精确金额场景用户需手动调整
		return "float64"
	case "CHAR", "VARCHAR", "TINYTEXT", "TEXT", "MEDIUMTEXT", "LONGTEXT", "ENUM", "SET":
		return "string"
	case "BLOB", "TINYBLOB", "MEDIUMBLOB", "LONGBLOB", "BINARY", "VARBINARY":
		return "[]byte"
	case "DATETIME", "TIMESTAMP", "TIME":
		return "time.Time"
	case "DATE":
		return "time.Time"
	case "BOOL", "BOOLEAN":
		return "bool"
	case "JSON":
		return "string"
	case "BIT":
		return "uint64"
	case "GEOMETRY", "POINT", "LINESTRING", "POLYGON":
		// 空间数据类型，映射为 string（实际使用时需要特定库）
		return "string"
	default:
		return "string"
	}
}

// pgTypeToGo 将 PostgreSQL 列类型映射为 Go 类型。
func pgTypeToGo(colType string) string {
	t := strings.ToUpper(colType)

	switch t {
	case "INTEGER", "INT", "INT4", "INT64":
		return "int64"
	case "BIGINT", "INT8":
		return "int64"
	case "SMALLINT", "INT2":
		return "int64"
	case "REAL", "FLOAT4":
		return "float64"
	case "DOUBLE PRECISION", "FLOAT8":
		return "float64"
	case "NUMERIC", "DECIMAL":
		return "float64"
	case "MONEY":
		return "float64"
	case "VARCHAR", "CHARACTER VARYING", "CHARACTER", "CHAR", "TEXT":
		return "string"
	case "BYTEA":
		return "[]byte"
	case "TIMESTAMP", "TIMESTAMP WITHOUT TIME ZONE", "TIMESTAMP WITH TIME ZONE", "TIMESTAMPTZ":
		return "time.Time"
	case "DATE":
		return "time.Time"
	case "TIME", "TIME WITHOUT TIME ZONE", "TIME WITH TIME ZONE", "TIMETZ":
		return "time.Time"
	case "INTERVAL":
		return "string"
	case "BOOLEAN", "BOOL":
		return "bool"
	case "UUID":
		return "string"
	case "JSON", "JSONB":
		return "string"
	case "XML":
		return "string"
	case "POINT", "LINE", "LSEG", "BOX", "PATH", "POLYGON", "CIRCLE":
		return "string"
	case "CIDR", "INET", "MACADDR", "MACADDR8":
		return "string"
	case "BIT", "VARBIT", "BIT VARYING":
		return "string"
	case "TSVECTOR", "TSQUERY":
		return "string"
	case "SERIAL", "BIGSERIAL", "SMALLSERIAL":
		return "int64"
	default:
		return "string"
	}
}
