package model

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/ngq/gorp/framework/contract"

	"github.com/spf13/cobra"
)

var (
	modelGenTable string
	modelGenOut   string
)

// modelGenCmd 根据数据库表结构生成一个基础 Go struct。
//
// 中文说明：
// - 它主要面向“先快速拿到模型骨架”这一需求。
// - 当前生成结果比较克制：只输出字段、db/json tag，不自动生成完整 CRUD。
// - 如果要进一步生成 service/http 层，可使用 `gorp model api`。
var modelGenCmd = &cobra.Command{
	Use:   "gen",
	Short: "Generate a simple struct model from DB table",
	RunE: func(cmd *cobra.Command, args []string) error {
		_, c, err := bootstrap()
		if err != nil {
			return err
		}
		insAny, err := c.Make(contract.DBInspectorKey)
		if err != nil {
			return err
		}
		ins := insAny.(contract.DBInspector)

		if modelGenTable == "" {
			return fmt.Errorf("--table is required")
		}
		cols, err := ins.Columns(cmd.Context(), modelGenTable)
		if err != nil {
			return err
		}

		outDir := modelGenOut
		if outDir == "" {
			outDir = filepath.Join("app", "model", "gen")
		}
		if err := os.MkdirAll(outDir, 0o755); err != nil {
			return err
		}

		data := struct {
			Table string
			Name  string
			Cols  []contract.Column
		}{
			Table: modelGenTable,
			Name:  toGoName(modelGenTable),
			Cols:  cols,
		}

		file := filepath.Join(outDir, strings.ToLower(data.Name)+".go")
		f, err := os.Create(file)
		if err != nil {
			return err
		}
		defer f.Close()

		tpl := template.Must(template.New("model").Funcs(template.FuncMap{
			"goType":   sqliteTypeToGo,
			"toGoName": toGoName,
		}).Parse(modelTpl))
		if err := tpl.Execute(f, data); err != nil {
			return err
		}
		fmt.Fprintf(cmd.OutOrStdout(), "generated: %s\n", file)
		return nil
	},
}

func init() {
	modelGenCmd.Flags().StringVar(&modelGenTable, "table", "", "table name")
	modelGenCmd.Flags().StringVar(&modelGenOut, "out", "", "output directory")
}

const modelTpl = `package gen

// Code generated by gorp model gen; DO NOT EDIT.

type {{.Name}} struct {
{{- range .Cols }}
	{{ toGoName .Name }} {{ goType .Type }} ` + "`db:\"{{.Name}}\" json:\"{{.Name}}\"`" + `
{{- end }}
}
`

func toGoName(s string) string {
	// 中文说明：
	// - 把 snake_case / kebab-case 表名字段名转成 Go 导出标识符。
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-'
	})
	for i := range parts {
		if len(parts[i]) == 0 {
			continue
		}
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return strings.Join(parts, "")
}

func sqliteTypeToGo(t string) string {
	// 中文说明：
	// - 这里采用的是“宽松映射”策略，优先满足快速生成可用代码。
	// - 当前对 sqlite 类型名做近似判断，因此更适合作为脚手架起点，而不是严格 schema 编译器。
	t = strings.ToUpper(t)
	switch {
	case strings.Contains(t, "INT"):
		return "int64"
	case strings.Contains(t, "CHAR"), strings.Contains(t, "TEXT"), strings.Contains(t, "CLOB"):
		return "string"
	case strings.Contains(t, "BLOB"):
		return "[]byte"
	case strings.Contains(t, "REAL"), strings.Contains(t, "FLOA"), strings.Contains(t, "DOUB"):
		return "float64"
	case strings.Contains(t, "BOOL"):
		return "bool"
	default:
		return "string"
	}
}
