//go:build !wireinject

// Code generated by Wire. DO NOT EDIT.

package main

import (
	"gorm.io/gorm"
	"grpc-demo/services/user/internal/service"
)

func wireUserServices(db *gorm.DB) (*service.Services, error) {
	services := service.NewServices(db)
	return services, nil
}
