// Code generated by Claude Code. DO NOT EDIT.

package main

import (
	"nop-go/services/notification-service/internal/biz"
	"nop-go/services/notification-service/internal/data"
	"nop-go/services/notification-service/internal/service"

	"gorm.io/gorm"
)

func wireNotificationService(db *gorm.DB) (*service.NotificationService, error) {
	notificationRepo := data.NewNotificationRepository(db)
	templateRepo := data.NewNotificationTemplateRepository(db)
	smsRepo := data.NewSMSRecordRepository(db)
	notificationUC := biz.NewNotificationUseCase(notificationRepo, templateRepo, smsRepo)
	templateUC := biz.NewTemplateUseCase(templateRepo)
	notificationService := service.NewNotificationService(notificationUC, templateUC)
	return notificationService, nil
}
