// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/message/v1/message.proto

package messagev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetMessageTemplateReq 获取消息模板请求
type GetMessageTemplateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 模板ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageTemplateReq) Reset() {
	*x = GetMessageTemplateReq{}
	mi := &file_api_message_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageTemplateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageTemplateReq) ProtoMessage() {}

func (x *GetMessageTemplateReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_message_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageTemplateReq.ProtoReflect.Descriptor instead.
func (*GetMessageTemplateReq) Descriptor() ([]byte, []int) {
	return file_api_message_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *GetMessageTemplateReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetMessageTemplateResp 获取消息模板响应
type GetMessageTemplateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                        // 模板ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                     // 模板名称
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`                               // 邮件主题
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`                                     // 邮件正文
	EmailAccount  string                 `protobuf:"bytes,5,opt,name=email_account,json=emailAccount,proto3" json:"email_account,omitempty"` // 发件邮箱账号
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`            // 是否启用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageTemplateResp) Reset() {
	*x = GetMessageTemplateResp{}
	mi := &file_api_message_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageTemplateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageTemplateResp) ProtoMessage() {}

func (x *GetMessageTemplateResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_message_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageTemplateResp.ProtoReflect.Descriptor instead.
func (*GetMessageTemplateResp) Descriptor() ([]byte, []int) {
	return file_api_message_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *GetMessageTemplateResp) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetMessageTemplateResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetMessageTemplateResp) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *GetMessageTemplateResp) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *GetMessageTemplateResp) GetEmailAccount() string {
	if x != nil {
		return x.EmailAccount
	}
	return ""
}

func (x *GetMessageTemplateResp) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

var File_api_message_v1_message_proto protoreflect.FileDescriptor

const file_api_message_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x1capi/message/v1/message.proto\x12\n" +
	"message.v1\"'\n" +
	"\x15GetMessageTemplateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\xac\x01\n" +
	"\x16GetMessageTemplateResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12#\n" +
	"\remail_account\x18\x05 \x01(\tR\femailAccount\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive2i\n" +
	"\n" +
	"MessageRPC\x12[\n" +
	"\x12GetMessageTemplate\x12!.message.v1.GetMessageTemplateReq\x1a\".message.v1.GetMessageTemplateRespB:Z8nop-go/services/message-service/api/message/v1;messagev1b\x06proto3"

var (
	file_api_message_v1_message_proto_rawDescOnce sync.Once
	file_api_message_v1_message_proto_rawDescData []byte
)

func file_api_message_v1_message_proto_rawDescGZIP() []byte {
	file_api_message_v1_message_proto_rawDescOnce.Do(func() {
		file_api_message_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_message_v1_message_proto_rawDesc), len(file_api_message_v1_message_proto_rawDesc)))
	})
	return file_api_message_v1_message_proto_rawDescData
}

var file_api_message_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_message_v1_message_proto_goTypes = []any{
	(*GetMessageTemplateReq)(nil),  // 0: message.v1.GetMessageTemplateReq
	(*GetMessageTemplateResp)(nil), // 1: message.v1.GetMessageTemplateResp
}
var file_api_message_v1_message_proto_depIdxs = []int32{
	0, // 0: message.v1.MessageRPC.GetMessageTemplate:input_type -> message.v1.GetMessageTemplateReq
	1, // 1: message.v1.MessageRPC.GetMessageTemplate:output_type -> message.v1.GetMessageTemplateResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_message_v1_message_proto_init() }
func file_api_message_v1_message_proto_init() {
	if File_api_message_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_message_v1_message_proto_rawDesc), len(file_api_message_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_message_v1_message_proto_goTypes,
		DependencyIndexes: file_api_message_v1_message_proto_depIdxs,
		MessageInfos:      file_api_message_v1_message_proto_msgTypes,
	}.Build()
	File_api_message_v1_message_proto = out.File
	file_api_message_v1_message_proto_goTypes = nil
	file_api_message_v1_message_proto_depIdxs = nil
}
