// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/message/v1/message.proto

package messagev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageRPC_GetMessageTemplate_FullMethodName = "/message.v1.MessageRPC/GetMessageTemplate"
)

// MessageRPCClient is the client API for MessageRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MessageRPC 消息服务 gRPC 接口 —— 定义其他服务需要跨服务调用的方法。
// 任何服务需要发送通知邮件时，可通过 GetMessageTemplate 获取模板内容。
type MessageRPCClient interface {
	// GetMessageTemplate 根据 ID 获取消息模板（其他服务发送通知时获取模板内容）
	GetMessageTemplate(ctx context.Context, in *GetMessageTemplateReq, opts ...grpc.CallOption) (*GetMessageTemplateResp, error)
}

type messageRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageRPCClient(cc grpc.ClientConnInterface) MessageRPCClient {
	return &messageRPCClient{cc}
}

func (c *messageRPCClient) GetMessageTemplate(ctx context.Context, in *GetMessageTemplateReq, opts ...grpc.CallOption) (*GetMessageTemplateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessageTemplateResp)
	err := c.cc.Invoke(ctx, MessageRPC_GetMessageTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageRPCServer is the server API for MessageRPC service.
// All implementations must embed UnimplementedMessageRPCServer
// for forward compatibility.
//
// MessageRPC 消息服务 gRPC 接口 —— 定义其他服务需要跨服务调用的方法。
// 任何服务需要发送通知邮件时，可通过 GetMessageTemplate 获取模板内容。
type MessageRPCServer interface {
	// GetMessageTemplate 根据 ID 获取消息模板（其他服务发送通知时获取模板内容）
	GetMessageTemplate(context.Context, *GetMessageTemplateReq) (*GetMessageTemplateResp, error)
	mustEmbedUnimplementedMessageRPCServer()
}

// UnimplementedMessageRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageRPCServer struct{}

func (UnimplementedMessageRPCServer) GetMessageTemplate(context.Context, *GetMessageTemplateReq) (*GetMessageTemplateResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessageTemplate not implemented")
}
func (UnimplementedMessageRPCServer) mustEmbedUnimplementedMessageRPCServer() {}
func (UnimplementedMessageRPCServer) testEmbeddedByValue()                    {}

// UnsafeMessageRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageRPCServer will
// result in compilation errors.
type UnsafeMessageRPCServer interface {
	mustEmbedUnimplementedMessageRPCServer()
}

func RegisterMessageRPCServer(s grpc.ServiceRegistrar, srv MessageRPCServer) {
	// If the following call panics, it indicates UnimplementedMessageRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageRPC_ServiceDesc, srv)
}

func _MessageRPC_GetMessageTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRPCServer).GetMessageTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRPC_GetMessageTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRPCServer).GetMessageTemplate(ctx, req.(*GetMessageTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageRPC_ServiceDesc is the grpc.ServiceDesc for MessageRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.v1.MessageRPC",
	HandlerType: (*MessageRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMessageTemplate",
			Handler:    _MessageRPC_GetMessageTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/message/v1/message.proto",
}
