FROM golang:1.26-alpine AS builder

WORKDIR /build

COPY shared/ ./shared/
COPY services/order/ ./services/order/

RUN cd /build/services/order && go build -o /order ./cmd

FROM alpine:3.19

RUN apk add --no-cache ca-certificates tzdata

WORKDIR /app

COPY services/order/config/app.yaml ./config/app.yaml
COPY --from=builder /order .

EXPOSE 8082

ENTRYPOINT ["./order"]
