// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/trade/v1/trade.proto

package tradev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TradeRPC_GetOrder_FullMethodName = "/trade.v1.TradeRPC/GetOrder"
)

// TradeRPCClient is the client API for TradeRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TradeRPC 交易服务 gRPC 接口 —— 定义其他服务可能需要跨服务调用的方法。
// 当前暂只有 GetOrder 供 gateway 或其他服务查询订单状态，后续可扩展。
type TradeRPCClient interface {
	// GetOrder 根据 ID 获取订单信息（供 gateway 查询订单状态）
	GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*GetOrderResp, error)
}

type tradeRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewTradeRPCClient(cc grpc.ClientConnInterface) TradeRPCClient {
	return &tradeRPCClient{cc}
}

func (c *tradeRPCClient) GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*GetOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderResp)
	err := c.cc.Invoke(ctx, TradeRPC_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradeRPCServer is the server API for TradeRPC service.
// All implementations must embed UnimplementedTradeRPCServer
// for forward compatibility.
//
// TradeRPC 交易服务 gRPC 接口 —— 定义其他服务可能需要跨服务调用的方法。
// 当前暂只有 GetOrder 供 gateway 或其他服务查询订单状态，后续可扩展。
type TradeRPCServer interface {
	// GetOrder 根据 ID 获取订单信息（供 gateway 查询订单状态）
	GetOrder(context.Context, *GetOrderReq) (*GetOrderResp, error)
	mustEmbedUnimplementedTradeRPCServer()
}

// UnimplementedTradeRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTradeRPCServer struct{}

func (UnimplementedTradeRPCServer) GetOrder(context.Context, *GetOrderReq) (*GetOrderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedTradeRPCServer) mustEmbedUnimplementedTradeRPCServer() {}
func (UnimplementedTradeRPCServer) testEmbeddedByValue()                  {}

// UnsafeTradeRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradeRPCServer will
// result in compilation errors.
type UnsafeTradeRPCServer interface {
	mustEmbedUnimplementedTradeRPCServer()
}

func RegisterTradeRPCServer(s grpc.ServiceRegistrar, srv TradeRPCServer) {
	// If the following call panics, it indicates UnimplementedTradeRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TradeRPC_ServiceDesc, srv)
}

func _TradeRPC_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeRPCServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeRPC_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeRPCServer).GetOrder(ctx, req.(*GetOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TradeRPC_ServiceDesc is the grpc.ServiceDesc for TradeRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradeRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trade.v1.TradeRPC",
	HandlerType: (*TradeRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrder",
			Handler:    _TradeRPC_GetOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/trade/v1/trade.proto",
}
