// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/trade/v1/trade.proto

package tradev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetOrderReq 获取订单请求
type GetOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 订单ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderReq) Reset() {
	*x = GetOrderReq{}
	mi := &file_api_trade_v1_trade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReq) ProtoMessage() {}

func (x *GetOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_trade_v1_trade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReq.ProtoReflect.Descriptor instead.
func (*GetOrderReq) Descriptor() ([]byte, []int) {
	return file_api_trade_v1_trade_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrderReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetOrderResp 获取订单响应
type GetOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                            // 订单ID
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                      // 用户ID
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                    // 订单状态
	TotalAmount   float64                `protobuf:"fixed64,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`     // 订单总额
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`                                // 货币
	ShippingAddr  string                 `protobuf:"bytes,6,opt,name=shipping_addr,json=shippingAddr,proto3" json:"shipping_addr,omitempty"`    // 收货地址
	PaymentMethod string                 `protobuf:"bytes,7,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"` // 支付方式
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`             // 创建时间
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`             // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResp) Reset() {
	*x = GetOrderResp{}
	mi := &file_api_trade_v1_trade_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResp) ProtoMessage() {}

func (x *GetOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_trade_v1_trade_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResp.ProtoReflect.Descriptor instead.
func (*GetOrderResp) Descriptor() ([]byte, []int) {
	return file_api_trade_v1_trade_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetOrderResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetOrderResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOrderResp) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *GetOrderResp) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetOrderResp) GetShippingAddr() string {
	if x != nil {
		return x.ShippingAddr
	}
	return ""
}

func (x *GetOrderResp) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *GetOrderResp) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetOrderResp) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_api_trade_v1_trade_proto protoreflect.FileDescriptor

const file_api_trade_v1_trade_proto_rawDesc = "" +
	"\n" +
	"\x18api/trade/v1/trade.proto\x12\btrade.v1\"\x1d\n" +
	"\vGetOrderReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x98\x02\n" +
	"\fGetOrderResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x01R\vtotalAmount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12#\n" +
	"\rshipping_addr\x18\x06 \x01(\tR\fshippingAddr\x12%\n" +
	"\x0epayment_method\x18\a \x01(\tR\rpaymentMethod\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt2E\n" +
	"\bTradeRPC\x129\n" +
	"\bGetOrder\x12\x15.trade.v1.GetOrderReq\x1a\x16.trade.v1.GetOrderRespB4Z2nop-go/services/trade-service/api/trade/v1;tradev1b\x06proto3"

var (
	file_api_trade_v1_trade_proto_rawDescOnce sync.Once
	file_api_trade_v1_trade_proto_rawDescData []byte
)

func file_api_trade_v1_trade_proto_rawDescGZIP() []byte {
	file_api_trade_v1_trade_proto_rawDescOnce.Do(func() {
		file_api_trade_v1_trade_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_trade_v1_trade_proto_rawDesc), len(file_api_trade_v1_trade_proto_rawDesc)))
	})
	return file_api_trade_v1_trade_proto_rawDescData
}

var file_api_trade_v1_trade_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_trade_v1_trade_proto_goTypes = []any{
	(*GetOrderReq)(nil),  // 0: trade.v1.GetOrderReq
	(*GetOrderResp)(nil), // 1: trade.v1.GetOrderResp
}
var file_api_trade_v1_trade_proto_depIdxs = []int32{
	0, // 0: trade.v1.TradeRPC.GetOrder:input_type -> trade.v1.GetOrderReq
	1, // 1: trade.v1.TradeRPC.GetOrder:output_type -> trade.v1.GetOrderResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_trade_v1_trade_proto_init() }
func file_api_trade_v1_trade_proto_init() {
	if File_api_trade_v1_trade_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_trade_v1_trade_proto_rawDesc), len(file_api_trade_v1_trade_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_trade_v1_trade_proto_goTypes,
		DependencyIndexes: file_api_trade_v1_trade_proto_depIdxs,
		MessageInfos:      file_api_trade_v1_trade_proto_msgTypes,
	}.Build()
	File_api_trade_v1_trade_proto = out.File
	file_api_trade_v1_trade_proto_goTypes = nil
	file_api_trade_v1_trade_proto_depIdxs = nil
}
