apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grpc-demo-staging

resources:
  - ../../base

images:
  - name: your-registry/grpc-demo-user-service
    newName: your-registry/grpc-demo-user-service
    newTag: staging
  - name: your-registry/grpc-demo-order-service
    newName: your-registry/grpc-demo-order-service
    newTag: staging
  - name: your-registry/grpc-demo-product-service
    newName: your-registry/grpc-demo-product-service
    newTag: staging

patches:
  - path: deployment-patch.yaml
