// Package proto provides proto generator implementation.
// This file implements typed RPC client wrapper generation from proto files.
//
// Proto 包提供 proto 生成器实现。
// 本文件实现从 proto 文件生成类型化 RPC 客户端 wrapper。
package proto

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	integrationcontract "github.com/ngq/gorp/framework/contract/integration"
)

// ProtoService describes one service parsed from proto file.
//
// ProtoService 描述从 proto 文件解析出的一个服务。
type ProtoService struct {
	Name    string
	Methods []ProtoMethod
}

// ProtoMethod describes one method parsed from proto service.
//
// ProtoMethod 描述从 proto 服务解析出的一个方法。
type ProtoMethod struct {
	Name         string
	RequestType  string
	ResponseType string
	InputStream  bool
	OutputStream bool
}

// GenClient generates typed RPC client wrapper from proto file.
// Parses the proto file to extract service and method definitions,
// then generates a Go file with typed client struct and methods.
//
// GenClient 从 proto 文件生成类型化 RPC 客户端 wrapper。
// 解析 proto 文件提取服务和方法的定义，
// 然后生成包含类型化客户端 struct 和方法的 Go 文件。
func (g *Generator) GenClient(ctx context.Context, opts integrationcontract.ClientGenOptions) error {
	if opts.ProtoFile == "" {
		return errors.New("proto file path is required")
	}
	if opts.OutputFile == "" {
		return errors.New("output file path is required")
	}
	if opts.PackageName == "" {
		// Derive package name from output directory
		// 从输出目录推导 package 名
		opts.PackageName = filepath.Base(filepath.Dir(opts.OutputFile))
		if opts.PackageName == "" || opts.PackageName == "." {
			opts.PackageName = "client"
		}
	}

	// Parse proto file to extract services
	// 解析 proto 文件提取服务
	services, err := parseProtoFile(opts.ProtoFile)
	if err != nil {
		return fmt.Errorf("parse proto file failed: %w", err)
	}

	// Filter service if specified
	// 如果指定了服务名则过滤
	if opts.ServiceName != "" {
		filtered := []ProtoService{}
		for _, svc := range services {
			if svc.Name == opts.ServiceName {
				filtered = append(filtered, svc)
			}
		}
		services = filtered
	}

	if len(services) == 0 {
		return errors.New("no services found in proto file")
	}

	// Generate client wrapper code
	// 生成客户端 wrapper 代码
	code := generateClientWrapperCode(services, opts)

	// Write output file
	// 写入输出文件
	outputDir := filepath.Dir(opts.OutputFile)
	if outputDir != "" && outputDir != "." {
		if err := os.MkdirAll(outputDir, 0755); err != nil {
			return fmt.Errorf("create output directory failed: %w", err)
		}
	}

	if err := os.WriteFile(opts.OutputFile, []byte(code), 0644); err != nil {
		return fmt.Errorf("write output file failed: %w", err)
	}

	return nil
}

// parseProtoFile parses a proto file and extracts service definitions.
// Uses regex-based parsing for simplicity and portability.
//
// parseProtoFile 解析 proto 文件并提取服务定义。
// 使用基于正则的解析以保持简单和可移植性。
func parseProtoFile(protoFile string) ([]ProtoService, error) {
	content, err := os.ReadFile(protoFile)
	if err != nil {
		return nil, fmt.Errorf("read proto file failed: %w", err)
	}

	services := []ProtoService{}

	// Regex patterns for service and method definitions
	// 用于匹配 service 和 method 定义的正则模式
	// 注意：service 匹配使用非贪婪模式，允许 rpc 方法体内包含 {}。
	servicePattern := regexp.MustCompile(`service\s+(\w+)\s*\{([\s\S]*?)\n\}`)
	methodPattern := regexp.MustCompile(`rpc\s+(\w+)\s*\(\s*(stream\s+)?(\w+)\s*\)\s*returns\s*\(\s*(stream\s+)?(\w+)\s*\)`)

	// Find all services
	// 查找所有服务
	serviceMatches := servicePattern.FindAllStringSubmatch(string(content), -1)
	for _, svcMatch := range serviceMatches {
		serviceName := svcMatch[1]
		serviceBody := svcMatch[2]

		methods := []ProtoMethod{}

		// Find all methods in the service
		// 查找服务中的所有方法
		methodMatches := methodPattern.FindAllStringSubmatch(serviceBody, -1)
		for i := range methodMatches {
			methodMatch := methodMatches[i]
			methodName := methodMatch[1]
			inputStream := strings.TrimSpace(methodMatch[2]) != ""
			requestType := methodMatch[3]
			outputStream := strings.TrimSpace(methodMatch[4]) != ""
			responseType := methodMatch[5]

			methods = append(methods, ProtoMethod{
				Name:         methodName,
				RequestType:  requestType,
				ResponseType: responseType,
				InputStream:  inputStream,
				OutputStream: outputStream,
			})
		}

		services = append(services, ProtoService{
			Name:    serviceName,
			Methods: methods,
		})
	}

	return services, nil
}

// generateClientWrapperCode generates Go code for typed RPC client wrapper.
//
// generateClientWrapperCode 生成类型化 RPC 客户端 wrapper 的 Go 代码。
func generateClientWrapperCode(services []ProtoService, opts integrationcontract.ClientGenOptions) string {
	var buf strings.Builder

	// File header
	// 文件头部
	buf.WriteString("// Code generated by gorp proto gen-client. DO NOT EDIT.\n")
	buf.WriteString("//\n")
	buf.WriteString("// 生成代码由 gorp proto gen-client 生成。请勿修改。\n")
	buf.WriteString("\n")
	buf.WriteString("package " + opts.PackageName + "\n\n")

	// Imports
	// 导入
	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\n")
	buf.WriteString("\ttransportcontract \"github.com/ngq/gorp/framework/contract/transport\"\n")
	buf.WriteString(")\n\n")

	// Generate pb import path based on proto file location
	// 根据 proto 文件位置生成 pb 导入路径
	protoDir := filepath.Dir(opts.ProtoFile)
	protoBase := filepath.Base(opts.ProtoFile)
	protoPkg := strings.TrimSuffix(protoBase, ".proto")

	// For pb import, we assume standard protoc output structure
	// 对于 pb 导入，假设使用标准 protoc 输出结构
	buf.WriteString("// Import generated protobuf types.\n")
	buf.WriteString("// 导入生成的 protobuf 类型。\n")
	buf.WriteString("//\n")
	buf.WriteString("// You may need to adjust the import path based on your protoc configuration.\n")
	buf.WriteString("// 可能需要根据 protoc 配置调整导入路径。\n")
	buf.WriteString("//\n")
	buf.WriteString("// Example: import pb \"" + protoDir + "/" + protoPkg + "\"\n")
	buf.WriteString("// 示例: import pb \"" + protoDir + "/" + protoPkg + "\"\n\n")

	// Generate client for each service
	// 为每个服务生成客户端
	for _, svc := range services {
		clientName := opts.ClientPrefix
		if clientName == "" {
			// Remove "Service" suffix if present
			// 如果存在 "Service" 后缀则去掉
			clientName = strings.TrimSuffix(svc.Name, "Service")
			if clientName == "" {
				clientName = svc.Name
			}
		}
		clientName += "Client"

		// Client struct
		// 客户端结构
		buf.WriteString("// " + clientName + " provides typed RPC client methods for " + svc.Name + ".\n")
		buf.WriteString("// Uses gorp's RPCClient with built-in governance capabilities.\n")
		buf.WriteString("//\n")
		buf.WriteString("// " + clientName + " 提供 " + svc.Name + " 的类型化 RPC 客户端方法。\n")
		buf.WriteString("// 使用 gorp 的 RPCClient，内置治理能力。\n")
		buf.WriteString("type " + clientName + " struct {\n")
		buf.WriteString("\tclient transportcontract.RPCClient\n")
		buf.WriteString("\tserviceName string\n")
		buf.WriteString("}\n\n")

		// Constructor
		// 构造函数
		buf.WriteString("// New" + clientName + " creates a new typed client wrapper.\n")
		buf.WriteString("// The RPCClient should be obtained from gorp container.\n")
		buf.WriteString("//\n")
		buf.WriteString("// New" + clientName + " 创建新的类型化客户端 wrapper。\n")
		buf.WriteString("// RPCClient 应从 gorp 容器获取。\n")
		buf.WriteString("func New" + clientName + "(client transportcontract.RPCClient) *" + clientName + " {\n")
		buf.WriteString("\treturn &" + clientName + "{\n")
		buf.WriteString("\t\tclient:      client,\n")
		buf.WriteString("\t\tserviceName: \"" + svc.Name + "\",\n")
		buf.WriteString("\t}\n")
		buf.WriteString("}\n\n")

		// Generate methods
		// 生成方法
		for _, method := range svc.Methods {
			// Skip streaming methods as they require special handling
			// 跳过流式方法，因为需要特殊处理
			if method.InputStream || method.OutputStream {
				buf.WriteString("// " + method.Name + " is a streaming method and requires special handling.\n")
				buf.WriteString("// Please use the raw RPCClient.Conn() for streaming RPC.\n")
				buf.WriteString("//\n")
				buf.WriteString("// " + method.Name + " 是流式方法，需要特殊处理。\n")
				buf.WriteString("// 请使用原始 RPCClient.Conn() 进行流式 RPC。\n\n")
				continue
			}

			buf.WriteString("// " + method.Name + " calls the " + method.Name + " RPC method.\n")
			buf.WriteString("// Automatically applies governance middleware (timeout, retry, etc).\n")
			buf.WriteString("//\n")
			buf.WriteString("// " + method.Name + " 调用 " + method.Name + " RPC 方法。\n")
			buf.WriteString("// 自动应用治理中间件（超时、重试等）。\n")
			buf.WriteString("func (c *" + clientName + ") " + method.Name + "(ctx context.Context, req *" + method.RequestType + ") (*" + method.ResponseType + ", error) {\n")
			buf.WriteString("\tresp := &" + method.ResponseType + "{}\n")
			buf.WriteString("\terr := c.client.Call(ctx, c.serviceName, \"" + method.Name + "\", req, resp)\n")
			buf.WriteString("\treturn resp, err\n")
			buf.WriteString("}\n\n")
		}
	}

	// Governance integration comment if requested
	// 如果请求则添加治理集成注释
	if opts.UseGovernance {
		buf.WriteString("// Governance Integration\n")
		buf.WriteString("// 治理集成\n")
		buf.WriteString("//\n")
		buf.WriteString("// The generated clients automatically benefit from gorp's governance capabilities:\n")
		buf.WriteString("// 生成的客户端自动享有 gorp 的治理能力：\n")
		buf.WriteString("//\n")
		buf.WriteString("// - Timeout: Configurable per-request timeout via RPCClient middleware.\n")
		buf.WriteString("// - Retry: Automatic retry on transient failures.\n")
		buf.WriteString("// - Circuit Breaker: Protection against cascading failures.\n")
		buf.WriteString("// - Tracing: Distributed tracing with OpenTelemetry.\n")
		buf.WriteString("// - Metadata: Automatic metadata propagation between services.\n")
		buf.WriteString("// - Service Auth: Token-based service-to-service authentication.\n")
		buf.WriteString("//\n")
		buf.WriteString("// Configure governance in your gorp application config:\n")
		buf.WriteString("// 在 gorp 应用配置中配置治理：\n")
		buf.WriteString("//\n")
		buf.WriteString("// governance:\n")
		buf.WriteString("//   mode: microservice\n")
		buf.WriteString("//   providers:\n")
		buf.WriteString("//     tracing: otel\n")
		buf.WriteString("//     circuitbreaker: sentinel\n")
		buf.WriteString("//\n")
	}

	return buf.String()
}
