// Code generated by Claude Code. DO NOT EDIT.

package main

import (
	"nop-go/services/affiliate-service/internal/biz"
	"nop-go/services/affiliate-service/internal/data"
	"nop-go/services/affiliate-service/internal/service"
	"nop-go/shared/bootstrap"

	"github.com/ngq/gorp/framework/contract"
	"gorm.io/gorm"
)

func affiliateConfigFromRuntime(rt *bootstrap.HTTPServiceRuntime) biz.AffiliateConfig {
	config := biz.AffiliateConfig{
		DefaultCommissionRate: rt.Config.GetFloat("affiliate.default_commission_rate"),
		MinCommissionAmount:   rt.Config.GetFloat("affiliate.min_commission_amount"),
		MinPayoutAmount:       rt.Config.GetFloat("affiliate.min_payout_amount"),
		CookieExpirationDays:  rt.Config.GetInt("affiliate.cookie_expiration_days"),
	}
	if config.DefaultCommissionRate <= 0 {
		config.DefaultCommissionRate = 5.0
	}
	if config.MinCommissionAmount <= 0 {
		config.MinCommissionAmount = 0.01
	}
	if config.MinPayoutAmount <= 0 {
		config.MinPayoutAmount = 50
	}
	if config.CookieExpirationDays <= 0 {
		config.CookieExpirationDays = 30
	}
	return config
}

func wireAffiliateService(db *gorm.DB, jwtSvc contract.JWTService, config biz.AffiliateConfig) (*service.AffiliateService, error) {
	affiliateRepo := data.NewAffiliateRepository(db)
	orderRepo := data.NewAffiliateOrderRepository(db)
	referralRepo := data.NewAffiliateReferralRepository(db)
	commissionRepo := data.NewAffiliateCommissionRepository(db)
	payoutRepo := data.NewAffiliatePayoutRepository(db)
	affUC := biz.NewAffiliateUseCase(affiliateRepo, orderRepo, referralRepo, commissionRepo, payoutRepo, config)
	affService := service.NewAffiliateService(affUC, jwtSvc)
	return affService, nil
}
