//go:build !wireinject

// Code generated by Wire. DO NOT EDIT.

package main

import (
	"nop-go/services/user-service/internal/service"
	"gorm.io/gorm"
)

// wireUserServices 用户服务依赖注入的生成代码。
// 合并了原 user 和 gdpr 服务的所有依赖链路。
func wireUserServices(db *gorm.DB) (*service.Services, error) {
	services := service.NewServices(db)
	return services, nil
}