//go:build !wireinject

// Code generated by Wire. DO NOT EDIT.

package main

import (
	"nop-go/services/store/internal/service"
	"gorm.io/gorm"
)

func wireStoreServices(db *gorm.DB) (*service.Services, error) {
	services := service.NewServices(db)
	return services, nil
}
