// Code generated by Claude Code. DO NOT EDIT.

package main

import (
	"fmt"

	"nop-go/shared/bootstrap"
	"nop-go/services/gateway-service/internal/service"
)

func gatewayRoutesFromRuntime(rt *bootstrap.HTTPServiceRuntime) ([]service.Route, error) {
	routes := rt.Config.Get("routes")
	items, ok := routes.([]any)
	if !ok {
		return nil, fmt.Errorf("gateway routes config is invalid")
	}

	mapped := make([]service.Route, 0, len(items))
	for _, item := range items {
		m, ok := item.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("gateway route item is invalid")
		}
		path, _ := m["path"].(string)
		target, _ := m["target"].(string)
		if path == "" || target == "" {
			return nil, fmt.Errorf("gateway route missing path or target")
		}
		mapped = append(mapped, service.Route{Path: path, Target: target})
	}
	return mapped, nil
}

func wireGatewayService(routes []service.Route) (*service.GatewayService, error) {
	gatewayService := service.NewGatewayService(routes)
	return gatewayService, nil
}
