FROM golang:1.22-alpine AS builder

WORKDIR /build

COPY shared/ ./shared/
COPY services/user/ ./services/user/

RUN cd /build/services/user && go build -o /user ./cmd

FROM alpine:3.19

RUN apk add --no-cache ca-certificates tzdata

WORKDIR /app

COPY services/user/config/app.yaml ./config/app.yaml
COPY --from=builder /user .

EXPOSE 8081

ENTRYPOINT ["./user"]
