FROM golang:1.22-alpine AS builder

WORKDIR /build

COPY shared/ ./shared/
COPY services/product/ ./services/product/

RUN cd /build/services/product && go build -o /product ./cmd

FROM alpine:3.19

RUN apk add --no-cache ca-certificates tzdata

WORKDIR /app

COPY services/product/config/app.yaml ./config/app.yaml
COPY --from=builder /product .

EXPOSE 8083

ENTRYPOINT ["./product"]
