// Code generated by Claude Code. DO NOT EDIT.

package main

import (
	"nop-go/services/customer-service/internal/biz"
	"nop-go/services/customer-service/internal/data"
	"nop-go/services/customer-service/internal/service"

	"github.com/ngq/gorp/framework/contract"
	"gorm.io/gorm"
)

func wireCustomerService(db *gorm.DB, jwtSvc contract.JWTService) (*service.CustomerService, error) {
	customerRepo := data.NewCustomerRepository(db)
	addressRepo := data.NewAddressRepository(db)
	roleRepo := data.NewCustomerRoleRepository(db)
	consentRepo := data.NewGdprConsentRepository(db)
	logRepo := data.NewGdprLogRepository(db)
	requestRepo := data.NewGdprRequestRepository(db)
	customerConsentRepo := data.NewCustomerConsentRepository(db)
	customerUC := biz.NewCustomerUseCase(customerRepo, addressRepo, roleRepo, jwtSvc)
	addressUC := biz.NewAddressUseCase(addressRepo)
	gdprUC := biz.NewGdprUseCase(consentRepo, logRepo, requestRepo, customerConsentRepo, customerRepo, addressRepo)
	customerService := service.NewCustomerService(customerUC, addressUC, gdprUC, jwtSvc)
	return customerService, nil
}
