// Code generated by Claude Code. DO NOT EDIT.

package main

import (
	"nop-go/services/media-service/internal/biz"
	"nop-go/services/media-service/internal/data"
	"nop-go/services/media-service/internal/service"

	securitycontract "github.com/ngq/gorp/framework/contract/security"
	"gorm.io/gorm"
)

// wireMediaService 浣跨敤鎺ヨ繎 multi-flat-wire 鐨勬柟寮忔敹鍙?media-service 鐨勮閰嶉摼銆?
func wireMediaService(db *gorm.DB, jwtSvc securitycontract.JWTService, localPath, urlPrefix, storageType string) (*service.MediaService, error) {
	storageConfig := biz.StorageConfig{
		Type:      storageType,
		LocalPath: localPath,
		URLPrefix: urlPrefix,
	}

	pictureRepo := data.NewPictureRepository(db)
	productPicRepo := data.NewProductPictureRepository(db)
	categoryPicRepo := data.NewCategoryPictureRepository(db)
	documentRepo := data.NewDocumentRepository(db)

	mediaUC := biz.NewMediaUseCase(pictureRepo, productPicRepo, categoryPicRepo, documentRepo, storageConfig)
	mediaService := service.NewMediaService(mediaUC, jwtSvc)
	return mediaService, nil
}
