// Code generated by Claude Code. DO NOT EDIT.

package main

import (
	"nop-go/services/media-service/internal/biz"
	"nop-go/services/media-service/internal/data"
	"nop-go/services/media-service/internal/service"

	"github.com/ngq/gorp/framework/contract"
	"gorm.io/gorm"
)

// wireMediaService 使用接近 multi-flat-wire 的方式收口 media-service 的装配链。
func wireMediaService(db *gorm.DB, jwtSvc contract.JWTService, localPath, urlPrefix, storageType string) (*service.MediaService, error) {
	storageConfig := biz.StorageConfig{
		Type:      storageType,
		LocalPath: localPath,
		URLPrefix: urlPrefix,
	}

	pictureRepo := data.NewPictureRepository(db)
	productPicRepo := data.NewProductPictureRepository(db)
	categoryPicRepo := data.NewCategoryPictureRepository(db)
	documentRepo := data.NewDocumentRepository(db)

	mediaUC := biz.NewMediaUseCase(pictureRepo, productPicRepo, categoryPicRepo, documentRepo, storageConfig)
	mediaService := service.NewMediaService(mediaUC, jwtSvc)
	return mediaService, nil
}
