# 开发环境 Deployment 补丁
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gorp-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: gorp-service
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"