# {{.ProjectName}}

.PHONY: generate gen-wire gen-proto build clean run-user run-order run-product test tidy deploy-local deploy-local-down

generate: gen-wire gen-proto

build:
	go build -o bin/user ./services/user/cmd
	go build -o bin/order ./services/order/cmd
	go build -o bin/product ./services/product/cmd

gen-wire:
	wire ./services/user/cmd
	wire ./services/order/cmd
	wire ./services/product/cmd

gen-proto:
	PATH="$(go env GOPATH)/bin:$$PATH" protoc -I . \
	  --go_out=. --go_opt=paths=source_relative \
	  --go-grpc_out=. --go-grpc_opt=paths=source_relative \
	  proto/user/v1/user.proto

tidy:
	go mod tidy

run-user:
	go run ./services/user/cmd

run-order:
	go run ./services/order/cmd

run-product:
	go run ./services/product/cmd

test:
	go test ./... -v

clean:
	rm -rf bin/
	rm -f *.db

deploy-local:
	docker-compose -f deployments/compose/docker-compose.yaml up -d

deploy-local-down:
	docker-compose -f deployments/compose/docker-compose.yaml down
