# {{.ProjectName}}

HARBOR_REGISTRY ?= harbor.example.com
HARBOR_NAMESPACE ?= {{.Name}}
IMAGE_TAG ?= latest

.PHONY: generate gen-wire gen-proto build clean run-user run-order run-product test tidy deploy-local deploy-local-down build-images deploy-local-build harbor-tag harbor-push

generate: gen-wire gen-proto

build:
	go build -o bin/user ./services/user/cmd
	go build -o bin/order ./services/order/cmd
	go build -o bin/product ./services/product/cmd

gen-wire:
	wire ./services/user/cmd
	wire ./services/order/cmd
	wire ./services/product/cmd

gen-proto:
	PATH="$(go env GOPATH)/bin:$$PATH" protoc -I . \
	  --go_out=. --go_opt=paths=source_relative \
	  --go-grpc_out=. --go-grpc_opt=paths=source_relative \
	  proto/user/v1/user.proto

tidy:
	go mod tidy

run-user:
	go run ./services/user/cmd

run-order:
	go run ./services/order/cmd

run-product:
	go run ./services/product/cmd

test:
	go test ./... -v

clean:
	rm -rf bin/
	rm -f *.db

build-images:
	docker build -f deploy/docker/Dockerfile.user -t user-service:$(IMAGE_TAG) .
	docker build -f deploy/docker/Dockerfile.order -t order-service:$(IMAGE_TAG) .
	docker build -f deploy/docker/Dockerfile.product -t product-service:$(IMAGE_TAG) .

deploy-local:
	docker-compose -f deploy/compose/docker-compose.yaml up -d

deploy-local-down:
	docker-compose -f deploy/compose/docker-compose.yaml down

deploy-local-build: build-images deploy-local

harbor-tag:
	docker tag user-service:$(IMAGE_TAG) $(HARBOR_REGISTRY)/$(HARBOR_NAMESPACE)/user-service:$(IMAGE_TAG)
	docker tag order-service:$(IMAGE_TAG) $(HARBOR_REGISTRY)/$(HARBOR_NAMESPACE)/order-service:$(IMAGE_TAG)
	docker tag product-service:$(IMAGE_TAG) $(HARBOR_REGISTRY)/$(HARBOR_NAMESPACE)/product-service:$(IMAGE_TAG)

harbor-push: build-images harbor-tag
	docker push $(HARBOR_REGISTRY)/$(HARBOR_NAMESPACE)/user-service:$(IMAGE_TAG)
	docker push $(HARBOR_REGISTRY)/$(HARBOR_NAMESPACE)/order-service:$(IMAGE_TAG)
	docker push $(HARBOR_REGISTRY)/$(HARBOR_NAMESPACE)/product-service:$(IMAGE_TAG)
