// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/admin/v1/admin.proto

package adminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetDiscountReq 获取优惠规则请求
type GetDiscountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 优惠ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiscountReq) Reset() {
	*x = GetDiscountReq{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiscountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiscountReq) ProtoMessage() {}

func (x *GetDiscountReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiscountReq.ProtoReflect.Descriptor instead.
func (*GetDiscountReq) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *GetDiscountReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetDiscountResp 获取优惠规则响应
type GetDiscountResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                            // 优惠ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                         // 优惠名称
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`                                         // 优惠码
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`                                        // 优惠类型:0-百分比,1-固定金额
	Value         float64                `protobuf:"fixed64,5,opt,name=value,proto3" json:"value,omitempty"`                                     // 优惠值
	MinAmount     float64                `protobuf:"fixed64,6,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`            // 最低消费金额
	MaxDiscount   float64                `protobuf:"fixed64,7,opt,name=max_discount,json=maxDiscount,proto3" json:"max_discount,omitempty"`      // 最大优惠金额
	StartTime     string                 `protobuf:"bytes,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`              // 生效开始时间
	EndTime       string                 `protobuf:"bytes,9,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                    // 生效结束时间
	TotalQuota    int32                  `protobuf:"varint,10,opt,name=total_quota,json=totalQuota,proto3" json:"total_quota,omitempty"`         // 总使用限额
	UsedQuota     int32                  `protobuf:"varint,11,opt,name=used_quota,json=usedQuota,proto3" json:"used_quota,omitempty"`            // 已使用次数
	PerUserLimit  int32                  `protobuf:"varint,12,opt,name=per_user_limit,json=perUserLimit,proto3" json:"per_user_limit,omitempty"` // 每人使用限额
	Status        int32                  `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`                                   // 状态:0-禁用,1-启用
	Description   string                 `protobuf:"bytes,14,opt,name=description,proto3" json:"description,omitempty"`                          // 描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiscountResp) Reset() {
	*x = GetDiscountResp{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiscountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiscountResp) ProtoMessage() {}

func (x *GetDiscountResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiscountResp.ProtoReflect.Descriptor instead.
func (*GetDiscountResp) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *GetDiscountResp) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetDiscountResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetDiscountResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetDiscountResp) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GetDiscountResp) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *GetDiscountResp) GetMinAmount() float64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *GetDiscountResp) GetMaxDiscount() float64 {
	if x != nil {
		return x.MaxDiscount
	}
	return 0
}

func (x *GetDiscountResp) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *GetDiscountResp) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *GetDiscountResp) GetTotalQuota() int32 {
	if x != nil {
		return x.TotalQuota
	}
	return 0
}

func (x *GetDiscountResp) GetUsedQuota() int32 {
	if x != nil {
		return x.UsedQuota
	}
	return 0
}

func (x *GetDiscountResp) GetPerUserLimit() int32 {
	if x != nil {
		return x.PerUserLimit
	}
	return 0
}

func (x *GetDiscountResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetDiscountResp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// GetDiscountByCodeReq 根据优惠码获取请求
type GetDiscountByCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // 优惠码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiscountByCodeReq) Reset() {
	*x = GetDiscountByCodeReq{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiscountByCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiscountByCodeReq) ProtoMessage() {}

func (x *GetDiscountByCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiscountByCodeReq.ProtoReflect.Descriptor instead.
func (*GetDiscountByCodeReq) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *GetDiscountByCodeReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// CheckPermissionReq 检查权限请求
type CheckPermissionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        uint32                 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` // 角色ID
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`            // 资源标识
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`                // 操作:read/write/delete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionReq) Reset() {
	*x = CheckPermissionReq{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionReq) ProtoMessage() {}

func (x *CheckPermissionReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionReq.ProtoReflect.Descriptor instead.
func (*CheckPermissionReq) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *CheckPermissionReq) GetRoleId() uint32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *CheckPermissionReq) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CheckPermissionReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// CheckPermissionResp 检查权限响应
type CheckPermissionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"` // 是否允许
	Effect        string                 `protobuf:"bytes,2,opt,name=effect,proto3" json:"effect,omitempty"`    // 效果:allow/deny
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionResp) Reset() {
	*x = CheckPermissionResp{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionResp) ProtoMessage() {}

func (x *CheckPermissionResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionResp.ProtoReflect.Descriptor instead.
func (*CheckPermissionResp) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *CheckPermissionResp) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckPermissionResp) GetEffect() string {
	if x != nil {
		return x.Effect
	}
	return ""
}

var File_api_admin_v1_admin_proto protoreflect.FileDescriptor

const file_api_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x18api/admin/v1/admin.proto\x12\badmin.v1\" \n" +
	"\x0eGetDiscountReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x8f\x03\n" +
	"\x0fGetDiscountResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x14\n" +
	"\x05value\x18\x05 \x01(\x01R\x05value\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x06 \x01(\x01R\tminAmount\x12!\n" +
	"\fmax_discount\x18\a \x01(\x01R\vmaxDiscount\x12\x1d\n" +
	"\n" +
	"start_time\x18\b \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\t \x01(\tR\aendTime\x12\x1f\n" +
	"\vtotal_quota\x18\n" +
	" \x01(\x05R\n" +
	"totalQuota\x12\x1d\n" +
	"\n" +
	"used_quota\x18\v \x01(\x05R\tusedQuota\x12$\n" +
	"\x0eper_user_limit\x18\f \x01(\x05R\fperUserLimit\x12\x16\n" +
	"\x06status\x18\r \x01(\x05R\x06status\x12 \n" +
	"\vdescription\x18\x0e \x01(\tR\vdescription\"*\n" +
	"\x14GetDiscountByCodeReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"a\n" +
	"\x12CheckPermissionReq\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\rR\x06roleId\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"G\n" +
	"\x13CheckPermissionResp\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06effect\x18\x02 \x01(\tR\x06effect2\xee\x01\n" +
	"\bAdminRPC\x12B\n" +
	"\vGetDiscount\x12\x18.admin.v1.GetDiscountReq\x1a\x19.admin.v1.GetDiscountResp\x12N\n" +
	"\x11GetDiscountByCode\x12\x1e.admin.v1.GetDiscountByCodeReq\x1a\x19.admin.v1.GetDiscountResp\x12N\n" +
	"\x0fCheckPermission\x12\x1c.admin.v1.CheckPermissionReq\x1a\x1d.admin.v1.CheckPermissionRespB4Z2nop-go/services/admin-service/api/admin/v1;adminv1b\x06proto3"

var (
	file_api_admin_v1_admin_proto_rawDescOnce sync.Once
	file_api_admin_v1_admin_proto_rawDescData []byte
)

func file_api_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_api_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_api_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_admin_v1_admin_proto_rawDesc), len(file_api_admin_v1_admin_proto_rawDesc)))
	})
	return file_api_admin_v1_admin_proto_rawDescData
}

var file_api_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_admin_v1_admin_proto_goTypes = []any{
	(*GetDiscountReq)(nil),       // 0: admin.v1.GetDiscountReq
	(*GetDiscountResp)(nil),      // 1: admin.v1.GetDiscountResp
	(*GetDiscountByCodeReq)(nil), // 2: admin.v1.GetDiscountByCodeReq
	(*CheckPermissionReq)(nil),   // 3: admin.v1.CheckPermissionReq
	(*CheckPermissionResp)(nil),  // 4: admin.v1.CheckPermissionResp
}
var file_api_admin_v1_admin_proto_depIdxs = []int32{
	0, // 0: admin.v1.AdminRPC.GetDiscount:input_type -> admin.v1.GetDiscountReq
	2, // 1: admin.v1.AdminRPC.GetDiscountByCode:input_type -> admin.v1.GetDiscountByCodeReq
	3, // 2: admin.v1.AdminRPC.CheckPermission:input_type -> admin.v1.CheckPermissionReq
	1, // 3: admin.v1.AdminRPC.GetDiscount:output_type -> admin.v1.GetDiscountResp
	1, // 4: admin.v1.AdminRPC.GetDiscountByCode:output_type -> admin.v1.GetDiscountResp
	4, // 5: admin.v1.AdminRPC.CheckPermission:output_type -> admin.v1.CheckPermissionResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_admin_v1_admin_proto_init() }
func file_api_admin_v1_admin_proto_init() {
	if File_api_admin_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_admin_v1_admin_proto_rawDesc), len(file_api_admin_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_api_admin_v1_admin_proto_depIdxs,
		MessageInfos:      file_api_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_api_admin_v1_admin_proto = out.File
	file_api_admin_v1_admin_proto_goTypes = nil
	file_api_admin_v1_admin_proto_depIdxs = nil
}
