// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/admin/v1/admin.proto

package adminv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminRPC_GetDiscount_FullMethodName       = "/admin.v1.AdminRPC/GetDiscount"
	AdminRPC_GetDiscountByCode_FullMethodName = "/admin.v1.AdminRPC/GetDiscountByCode"
	AdminRPC_CheckPermission_FullMethodName   = "/admin.v1.AdminRPC/CheckPermission"
)

// AdminRPCClient is the client API for AdminRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminRPC 管理服务 gRPC 接口 —— 定义其他服务（trade-service）需要跨服务调用的方法。
// trade-service 结算时需要调用 GetDiscount 和 GetDiscountByCode，
// admin 权限检查需要调用 CheckPermission（未来 gateway 也可使用）。
// 注意：税率查询（GetTaxRate）属于 trade-service 自身，不在 admin-service 中。
type AdminRPCClient interface {
	// GetDiscount 根据 ID 获取优惠规则（trade 结算时计算折扣）
	GetDiscount(ctx context.Context, in *GetDiscountReq, opts ...grpc.CallOption) (*GetDiscountResp, error)
	// GetDiscountByCode 根据优惠码获取优惠规则（trade 结算时验证优惠码）
	GetDiscountByCode(ctx context.Context, in *GetDiscountByCodeReq, opts ...grpc.CallOption) (*GetDiscountResp, error)
	// CheckPermission 检查权限（admin 权限检查、gateway 接口鉴权）
	CheckPermission(ctx context.Context, in *CheckPermissionReq, opts ...grpc.CallOption) (*CheckPermissionResp, error)
}

type adminRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminRPCClient(cc grpc.ClientConnInterface) AdminRPCClient {
	return &adminRPCClient{cc}
}

func (c *adminRPCClient) GetDiscount(ctx context.Context, in *GetDiscountReq, opts ...grpc.CallOption) (*GetDiscountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiscountResp)
	err := c.cc.Invoke(ctx, AdminRPC_GetDiscount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRPCClient) GetDiscountByCode(ctx context.Context, in *GetDiscountByCodeReq, opts ...grpc.CallOption) (*GetDiscountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiscountResp)
	err := c.cc.Invoke(ctx, AdminRPC_GetDiscountByCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRPCClient) CheckPermission(ctx context.Context, in *CheckPermissionReq, opts ...grpc.CallOption) (*CheckPermissionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPermissionResp)
	err := c.cc.Invoke(ctx, AdminRPC_CheckPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminRPCServer is the server API for AdminRPC service.
// All implementations must embed UnimplementedAdminRPCServer
// for forward compatibility.
//
// AdminRPC 管理服务 gRPC 接口 —— 定义其他服务（trade-service）需要跨服务调用的方法。
// trade-service 结算时需要调用 GetDiscount 和 GetDiscountByCode，
// admin 权限检查需要调用 CheckPermission（未来 gateway 也可使用）。
// 注意：税率查询（GetTaxRate）属于 trade-service 自身，不在 admin-service 中。
type AdminRPCServer interface {
	// GetDiscount 根据 ID 获取优惠规则（trade 结算时计算折扣）
	GetDiscount(context.Context, *GetDiscountReq) (*GetDiscountResp, error)
	// GetDiscountByCode 根据优惠码获取优惠规则（trade 结算时验证优惠码）
	GetDiscountByCode(context.Context, *GetDiscountByCodeReq) (*GetDiscountResp, error)
	// CheckPermission 检查权限（admin 权限检查、gateway 接口鉴权）
	CheckPermission(context.Context, *CheckPermissionReq) (*CheckPermissionResp, error)
	mustEmbedUnimplementedAdminRPCServer()
}

// UnimplementedAdminRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminRPCServer struct{}

func (UnimplementedAdminRPCServer) GetDiscount(context.Context, *GetDiscountReq) (*GetDiscountResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiscount not implemented")
}
func (UnimplementedAdminRPCServer) GetDiscountByCode(context.Context, *GetDiscountByCodeReq) (*GetDiscountResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiscountByCode not implemented")
}
func (UnimplementedAdminRPCServer) CheckPermission(context.Context, *CheckPermissionReq) (*CheckPermissionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckPermission not implemented")
}
func (UnimplementedAdminRPCServer) mustEmbedUnimplementedAdminRPCServer() {}
func (UnimplementedAdminRPCServer) testEmbeddedByValue()                  {}

// UnsafeAdminRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminRPCServer will
// result in compilation errors.
type UnsafeAdminRPCServer interface {
	mustEmbedUnimplementedAdminRPCServer()
}

func RegisterAdminRPCServer(s grpc.ServiceRegistrar, srv AdminRPCServer) {
	// If the following call panics, it indicates UnimplementedAdminRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminRPC_ServiceDesc, srv)
}

func _AdminRPC_GetDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiscountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRPCServer).GetDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRPC_GetDiscount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRPCServer).GetDiscount(ctx, req.(*GetDiscountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRPC_GetDiscountByCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiscountByCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRPCServer).GetDiscountByCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRPC_GetDiscountByCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRPCServer).GetDiscountByCode(ctx, req.(*GetDiscountByCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRPC_CheckPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPermissionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRPCServer).CheckPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRPC_CheckPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRPCServer).CheckPermission(ctx, req.(*CheckPermissionReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminRPC_ServiceDesc is the grpc.ServiceDesc for AdminRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.v1.AdminRPC",
	HandlerType: (*AdminRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDiscount",
			Handler:    _AdminRPC_GetDiscount_Handler,
		},
		{
			MethodName: "GetDiscountByCode",
			Handler:    _AdminRPC_GetDiscountByCode_Handler,
		},
		{
			MethodName: "CheckPermission",
			Handler:    _AdminRPC_CheckPermission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/admin/v1/admin.proto",
}
