// Code generated by Claude Code. DO NOT EDIT.

package main

import (
	"nop-go/services/seo-service/internal/biz"
	"nop-go/services/seo-service/internal/data"
	"nop-go/services/seo-service/internal/service"

	securitycontract "github.com/ngq/gorp/framework/contract/security"
	"gorm.io/gorm"
)

// wireSEOService 浣跨敤鎺ヨ繎 multi-flat-wire 鐨勬柟寮忔敹鍙?seo-service 鐨勮閰嶉摼銆?
func wireSEOService(db *gorm.DB, jwtSvc securitycontract.JWTService, enabled, sitemapEnabled, canonicalUrlsEnabled, customMetaEnabled bool) (*service.SEOService, error) {
	config := biz.SEOConfig{
		Enabled:              enabled,
		SitemapEnabled:       sitemapEnabled,
		CanonicalUrlsEnabled: canonicalUrlsEnabled,
		CustomMetaEnabled:    customMetaEnabled,
	}

	urlRecordRepo := data.NewUrlRecordRepository(db)
	urlRedirectRepo := data.NewUrlRedirectRepository(db)
	metaInfoRepo := data.NewMetaInfoRepository(db)
	sitemapNodeRepo := data.NewSitemapNodeRepository(db)

	seoUC := biz.NewSEOUseCase(urlRecordRepo, urlRedirectRepo, metaInfoRepo, sitemapNodeRepo, config)
	seoService := service.NewSEOService(seoUC, jwtSvc)
	return seoService, nil
}
