// Code generated by Claude Code. DO NOT EDIT.

package main

import (
	"nop-go/services/seo-service/internal/biz"
	"nop-go/services/seo-service/internal/data"
	"nop-go/services/seo-service/internal/service"

	"github.com/ngq/gorp/framework/contract"
	"gorm.io/gorm"
)

// wireSEOService 使用接近 multi-flat-wire 的方式收口 seo-service 的装配链。
func wireSEOService(db *gorm.DB, jwtSvc contract.JWTService, enabled, sitemapEnabled, canonicalUrlsEnabled, customMetaEnabled bool) (*service.SEOService, error) {
	config := biz.SEOConfig{
		Enabled:              enabled,
		SitemapEnabled:       sitemapEnabled,
		CanonicalUrlsEnabled: canonicalUrlsEnabled,
		CustomMetaEnabled:    customMetaEnabled,
	}

	urlRecordRepo := data.NewUrlRecordRepository(db)
	urlRedirectRepo := data.NewUrlRedirectRepository(db)
	metaInfoRepo := data.NewMetaInfoRepository(db)
	sitemapNodeRepo := data.NewSitemapNodeRepository(db)

	seoUC := biz.NewSEOUseCase(urlRecordRepo, urlRedirectRepo, metaInfoRepo, sitemapNodeRepo, config)
	seoService := service.NewSEOService(seoUC, jwtSvc)
	return seoService, nil
}
