// Code generated by Claude Code. DO NOT EDIT.

package main

import (
	"nop-go/shared/plugin"
	"nop-go/services/payment-service/internal/biz"
	"nop-go/services/payment-service/internal/data"
	"nop-go/services/payment-service/internal/service"

	"gorm.io/gorm"
)

func wirePaymentService(db *gorm.DB, registry *plugin.Registry) (*service.PaymentService, error) {
	paymentRepo := data.NewPaymentRepository(db)
	transactionRepo := data.NewPaymentTransactionRepository(db)
	refundRepo := data.NewRefundRepository(db)
	paymentUC := biz.NewPaymentUseCase(paymentRepo, transactionRepo, refundRepo, registry)
	paymentService := service.NewPaymentService(paymentUC)
	return paymentService, nil
}
