app:
  name: shipping-service
  env: development
  address: ":8012"

database:
  driver: mysql
  dsn: "root:nop123456@tcp(mysql:3306)/nop_shipping?charset=utf8mb4&parseTime=True&loc=Local"
  max_open_conns: 50
  max_idle_conns: 10

redis:
  addr: "redis:6379"
  password: ""
  db: 0

log:
  level: debug

discovery:
  enabled: false
  type: consul
  consul:
    addr: "consul:8500"
    service_name: "shipping-service"

services:
  order: "http://order:8005"
  notification: "http://notification:8009"