// Code generated by Claude Code. DO NOT EDIT.

package main

import (
	"nop-go/shared/dlock"
	"nop-go/services/inventory-service/internal/biz"
	"nop-go/services/inventory-service/internal/data"
	"nop-go/services/inventory-service/internal/service"

	"gorm.io/gorm"
)

func wireInventoryService(db *gorm.DB, lockMgr *dlock.LockManager) (*service.InventoryService, error) {
	inventoryRepo := data.NewInventoryRepository(db)
	warehouseRepo := data.NewWarehouseRepository(db)
	reservationRepo := data.NewStockReservationRepository(db)
	logRepo := data.NewInventoryLogRepository(db)
	inventoryUC := biz.NewInventoryUseCase(inventoryRepo, warehouseRepo, reservationRepo, logRepo, lockMgr)
	warehouseUC := biz.NewWarehouseUseCase(warehouseRepo)
	inventoryService := service.NewInventoryService(inventoryUC, warehouseUC)
	return inventoryService, nil
}
