// Code generated by Claude Code. DO NOT EDIT.

package main

import (
	"nop-go/services/admin-service/internal/biz"
	"nop-go/services/admin-service/internal/data"
	"nop-go/services/admin-service/internal/service"

	"github.com/ngq/gorp/framework/contract"
	"gorm.io/gorm"
)

func wireAdminService(db *gorm.DB, jwtSvc contract.JWTService) (*service.AdminService, error) {
	userRepo := data.NewAdminUserRepository(db)
	roleRepo := data.NewAdminRoleRepository(db)
	permissionRepo := data.NewAdminPermissionRepository(db)
	settingRepo := data.NewSettingRepository(db)
	logRepo := data.NewActivityLogRepository(db)
	userUC := biz.NewAdminUserUseCase(userRepo, roleRepo, logRepo, jwtSvc)
	roleUC := biz.NewAdminRoleUseCase(roleRepo, permissionRepo)
	settingUC := biz.NewSettingUseCase(settingRepo)
	logUC := biz.NewActivityLogUseCase(logRepo)
	adminService := service.NewAdminService(userUC, roleUC, settingUC, logUC, jwtSvc)
	return adminService, nil
}
