//go:build !wireinject

// Code generated by Wire. DO NOT EDIT.

package main

import (
	"nop-go/services/admin-service/internal/service"

	"gorm.io/gorm"
)

// wireAdminServices 通过 Wire 注入数据库连接，构建管理后台服务实例
func wireAdminServices(db *gorm.DB) (*service.Services, error) {
	services := service.NewServices(db)
	return services, nil
}