# {{.ProjectName}}

HARBOR_REGISTRY ?= harbor.example.com
HARBOR_NAMESPACE ?= {{.Name}}
IMAGE_TAG ?= latest
USER_IMAGE ?= {{.KubernetesName}}-user-service
ORDER_IMAGE ?= {{.KubernetesName}}-order-service
PRODUCT_IMAGE ?= {{.KubernetesName}}-product-service

.PHONY: generate gen-wire build clean run-user run-order run-product test tidy deploy-local deploy-local-down build-images deploy-local-build harbor-tag harbor-push

generate: gen-wire

gen-wire:
	wire ./services/user/cmd
	wire ./services/order/cmd
	wire ./services/product/cmd

build:
	go build -o bin/user ./services/user/cmd
	go build -o bin/order ./services/order/cmd
	go build -o bin/product ./services/product/cmd

tidy:
	go work sync

run-user:
	go run ./services/user/cmd

run-order:
	go run ./services/order/cmd

run-product:
	go run ./services/product/cmd

test:
	go test ./services/user/... ./services/order/... ./services/product/... ./shared/... -v

clean:
	rm -rf bin/
	rm -f *.db

build-images:
	docker build -f deploy/docker/Dockerfile.user -t $(USER_IMAGE):$(IMAGE_TAG) .
	docker build -f deploy/docker/Dockerfile.order -t $(ORDER_IMAGE):$(IMAGE_TAG) .
	docker build -f deploy/docker/Dockerfile.product -t $(PRODUCT_IMAGE):$(IMAGE_TAG) .

deploy-local:
	docker-compose -f deploy/compose/docker-compose.yaml up -d

deploy-local-down:
	docker-compose -f deploy/compose/docker-compose.yaml down

deploy-local-build: build-images deploy-local

harbor-tag:
	docker tag $(USER_IMAGE):$(IMAGE_TAG) $(HARBOR_REGISTRY)/$(HARBOR_NAMESPACE)/$(USER_IMAGE):$(IMAGE_TAG)
	docker tag $(ORDER_IMAGE):$(IMAGE_TAG) $(HARBOR_REGISTRY)/$(HARBOR_NAMESPACE)/$(ORDER_IMAGE):$(IMAGE_TAG)
	docker tag $(PRODUCT_IMAGE):$(IMAGE_TAG) $(HARBOR_REGISTRY)/$(HARBOR_NAMESPACE)/$(PRODUCT_IMAGE):$(IMAGE_TAG)

harbor-push: build-images harbor-tag
	docker push $(HARBOR_REGISTRY)/$(HARBOR_NAMESPACE)/$(USER_IMAGE):$(IMAGE_TAG)
	docker push $(HARBOR_REGISTRY)/$(HARBOR_NAMESPACE)/$(ORDER_IMAGE):$(IMAGE_TAG)
	docker push $(HARBOR_REGISTRY)/$(HARBOR_NAMESPACE)/$(PRODUCT_IMAGE):$(IMAGE_TAG)
