.PHONY: build clean run-user run-order run-product test tidy

build:
	CGO_ENABLED=1 go build -o bin/user ./services/user/cmd
	CGO_ENABLED=1 go build -o bin/order ./services/order/cmd
	CGO_ENABLED=1 go build -o bin/product ./services/product/cmd

tidy:
	go work sync

run-user:
	go run ./services/user/cmd

run-order:
	go run ./services/order/cmd

run-product:
	go run ./services/product/cmd

test:
	go test ./... -v

clean:
	rm -rf bin/
	rm -f *.db

deploy-local:
	docker-compose -f deploy/compose/docker-compose.yaml up -d

deploy-local-down:
	docker-compose -f deploy/compose/docker-compose.yaml down
