// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/content/v1/content.proto

package contentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetBlogReq 获取博客请求
type GetBlogReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 博客ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlogReq) Reset() {
	*x = GetBlogReq{}
	mi := &file_api_content_v1_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogReq) ProtoMessage() {}

func (x *GetBlogReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogReq.ProtoReflect.Descriptor instead.
func (*GetBlogReq) Descriptor() ([]byte, []int) {
	return file_api_content_v1_content_proto_rawDescGZIP(), []int{0}
}

func (x *GetBlogReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetBlogResp 获取博客响应
type GetBlogResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                               // 博客ID
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                          // 标题
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                      // 正文
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`                        // 作者
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                        // 状态
	Tags          string                 `protobuf:"bytes,6,opt,name=tags,proto3" json:"tags,omitempty"`                            // 标签
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 创建时间
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlogResp) Reset() {
	*x = GetBlogResp{}
	mi := &file_api_content_v1_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogResp) ProtoMessage() {}

func (x *GetBlogResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_v1_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogResp.ProtoReflect.Descriptor instead.
func (*GetBlogResp) Descriptor() ([]byte, []int) {
	return file_api_content_v1_content_proto_rawDescGZIP(), []int{1}
}

func (x *GetBlogResp) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetBlogResp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetBlogResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetBlogResp) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *GetBlogResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetBlogResp) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *GetBlogResp) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetBlogResp) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_api_content_v1_content_proto protoreflect.FileDescriptor

const file_api_content_v1_content_proto_rawDesc = "" +
	"\n" +
	"\x1capi/content/v1/content.proto\x12\n" +
	"content.v1\"\x1c\n" +
	"\n" +
	"GetBlogReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xcf\x01\n" +
	"\vGetBlogResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x12\n" +
	"\x04tags\x18\x06 \x01(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt2H\n" +
	"\n" +
	"ContentRPC\x12:\n" +
	"\aGetBlog\x12\x16.content.v1.GetBlogReq\x1a\x17.content.v1.GetBlogRespB:Z8nop-go/services/content-service/api/content/v1;contentv1b\x06proto3"

var (
	file_api_content_v1_content_proto_rawDescOnce sync.Once
	file_api_content_v1_content_proto_rawDescData []byte
)

func file_api_content_v1_content_proto_rawDescGZIP() []byte {
	file_api_content_v1_content_proto_rawDescOnce.Do(func() {
		file_api_content_v1_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_content_v1_content_proto_rawDesc), len(file_api_content_v1_content_proto_rawDesc)))
	})
	return file_api_content_v1_content_proto_rawDescData
}

var file_api_content_v1_content_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_content_v1_content_proto_goTypes = []any{
	(*GetBlogReq)(nil),  // 0: content.v1.GetBlogReq
	(*GetBlogResp)(nil), // 1: content.v1.GetBlogResp
}
var file_api_content_v1_content_proto_depIdxs = []int32{
	0, // 0: content.v1.ContentRPC.GetBlog:input_type -> content.v1.GetBlogReq
	1, // 1: content.v1.ContentRPC.GetBlog:output_type -> content.v1.GetBlogResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_content_v1_content_proto_init() }
func file_api_content_v1_content_proto_init() {
	if File_api_content_v1_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_content_v1_content_proto_rawDesc), len(file_api_content_v1_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_content_v1_content_proto_goTypes,
		DependencyIndexes: file_api_content_v1_content_proto_depIdxs,
		MessageInfos:      file_api_content_v1_content_proto_msgTypes,
	}.Build()
	File_api_content_v1_content_proto = out.File
	file_api_content_v1_content_proto_goTypes = nil
	file_api_content_v1_content_proto_depIdxs = nil
}
