//go:build !wireinject

// Code generated by Wire. DO NOT EDIT.

// Package main Wire 生成的依赖注入实现。
//
// 此文件由 wire 工具根据 wire.go 自动生成，请勿手动修改。
// 重新生成命令：wire ./cmd/
package main

import (
	"nop-go/services/message-service/internal/service"

	"gorm.io/gorm"
)

// wireMessageServices 构建消息服务集合。
//
// 直接调用 service.NewServices 创建服务实例，
// 内部完成 data → biz → service 的依赖链组装。
func wireMessageServices(db *gorm.DB) (*service.Services, error) {
	services := service.NewServices(db)
	return services, nil
}
