package cmd

import (
	"testing"

	frameworktesting "github.com/ngq/gorp/framework/testing"
	"github.com/stretchr/testify/require"
)

func TestGeneratedManualIndexDoesNotMentionLegacyRuntimePaths(t *testing.T) {
	require.NoError(t, frameworktesting.ChdirRepoRoot())

	index := renderIndexDoc()
	require.Contains(t, index, "当前 CLI 主线已不再把 `app / grpc / cron / build / dev / deploy` 作为 starter 项目的公开 runtime 路径")
	require.NotContains(t, index, "legacy runtime 命令组（兼容/专项）：`gorp app`、`gorp cron`、`gorp grpc`")
}

func TestGeneratedManualPagesDeclareAutoGeneratedBoundary(t *testing.T) {
	require.NoError(t, frameworktesting.ChdirRepoRoot())

	index := renderIndexDoc()
	require.Contains(t, index, "自动生成页范围：`index.md`、`cli.md`、`config.md`")
	require.Contains(t, index, "其余 `docs/manual/*.md` 默认按长期手工手册维护")

	cliDoc, err := renderCLIDoc(rootCmd)
	require.NoError(t, err)
	require.Contains(t, cliDoc, "自动生成边界：本页与 `index.md`、`config.md` 属于自动参考页")

	configDoc, err := renderConfigDoc("E:/project/gin_plantfrom", "", true)
	require.NoError(t, err)
	require.Contains(t, configDoc, "自动生成边界：这里只承载配置聚合视图")
}
