//go:build !wireinject

// Code generated by Wire. DO NOT EDIT.

package main

import (
	"github.com/ngq/gorp"
	"gorm.io/gorm"
	"grpc-demo/services/order/internal/service"
)

func wireOrderServices(db *gorm.DB, userConnFactory gorp.GRPCConnFactory, dlock gorp.DistributedLock) (*service.Services, error) {
	services := service.NewServices(db, userConnFactory, dlock)
	return services, nil
}
