// Package pb provides test protobuf definitions for integration tests.
// This file is manually created for testing (not generated by protoc).
//
// 本包提供集成测试用的 protobuf 定义。
// 本文件手动创建用于测试（非 protoc 生成的代码）。
package pb

import (
	"context"

	"google.golang.org/grpc"
)

// HelloRequest represents a simple hello request.
//
// HelloRequest 表示简单的 hello 请求。
type HelloRequest struct {
	Name string
}

// HelloResponse represents a hello response.
//
// HelloResponse 表示 hello 响应。
type HelloResponse struct {
	Message   string
	TraceId   string
	RequestId string
}

// EchoRequest represents an echo request.
//
// EchoRequest 表示 echo 请求。
type EchoRequest struct {
	Body string
}

// EchoResponse represents an echo response.
//
// EchoResponse 表示 echo 响应。
type EchoResponse struct {
	Body     string
	Metadata map[string]string
}

// StreamRequest represents a stream request.
//
// StreamRequest 表示 stream 请求。
type StreamRequest struct {
	Count int32
}

// StreamResponse represents a stream response.
//
// StreamResponse 表示 stream 响应。
type StreamResponse struct {
	Index   int32
	Message string
}

// TestService_StreamTestServer is the server stream for StreamTest.
//
// TestService_StreamTestServer 是 StreamTest 的服务端 stream。
type TestService_StreamTestServer interface {
	Send(*StreamResponse) error
	grpc.ServerStream
}

// TestServiceClient is the client API for TestService.
//
// TestServiceClient 是 TestService 的客户端 API。
type TestServiceClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	StreamTest(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ClientStream, error)
}

// testServiceClient implements TestServiceClient.
//
// testServiceClient 实现 TestServiceClient。
type testServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewTestServiceClient creates a new TestServiceClient.
//
// NewTestServiceClient 创建新的 TestServiceClient。
func NewTestServiceClient(cc grpc.ClientConnInterface) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/gorp.test.TestService/SayHello", in, out, opts...)
	return out, err
}

func (c *testServiceClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, "/gorp.test.TestService/Echo", in, out, opts...)
	return out, err
}

func (c *testServiceClient) StreamTest(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ClientStream, error) {
	stream, err := c.cc.NewStream(ctx, &grpc.StreamDesc{
		ServerStreams: true,
	}, "/gorp.test.TestService/StreamTest", opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.SendMsg(in); err != nil {
		return nil, err
	}
	return stream, nil
}

// TestServiceServer is the server API for TestService.
//
// TestServiceServer 是 TestService 的服务端 API。
type TestServiceServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	StreamTest(*StreamRequest, TestService_StreamTestServer) error
}

// UnimplementedTestServiceServer must be embedded for forward compatibility.
//
// UnimplementedTestServiceServer 必须嵌入以保持向前兼容。
type UnimplementedTestServiceServer struct{}

func (UnimplementedTestServiceServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, nil
}

func (UnimplementedTestServiceServer) Echo(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, nil
}

func (UnimplementedTestServiceServer) StreamTest(*StreamRequest, TestService_StreamTestServer) error {
	return nil
}

// RegisterTestServiceServer registers TestServiceServer.
//
// RegisterTestServiceServer 注册 TestServiceServer。
func RegisterTestServiceServer(s grpc.ServiceRegistrar, srv TestServiceServer) {
	s.RegisterService(&grpc.ServiceDesc{
		ServiceName: "gorp.test.TestService",
		HandlerType: (*TestServiceServer)(nil),
		Methods: []grpc.MethodDesc{
			{
				MethodName: "SayHello",
				Handler:    _TestService_SayHello_Handler,
			},
			{
				MethodName: "Echo",
				Handler:    _TestService_Echo_Handler,
			},
		},
		Streams: []grpc.StreamDesc{
			{
				StreamName:    "StreamTest",
				Handler:       _TestService_StreamTest_Handler,
				ServerStreams: true,
			},
		},
	}, srv)
}

func _TestService_SayHello_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	return srv.(TestServiceServer).SayHello(ctx, in)
}

func _TestService_Echo_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	return srv.(TestServiceServer).Echo(ctx, in)
}

func _TestService_StreamTest_Handler(srv any, stream grpc.ServerStream) error {
	in := new(StreamRequest)
	if err := stream.RecvMsg(in); err != nil {
		return err
	}
	return srv.(TestServiceServer).StreamTest(in, &testServiceStreamTestServer{stream})
}

// testServiceStreamTestServer wraps grpc.ServerStream for StreamTest.
type testServiceStreamTestServer struct {
	grpc.ServerStream
}

func (s *testServiceStreamTestServer) Send(m *StreamResponse) error {
	return s.ServerStream.SendMsg(m)
}