FROM golang:1.24 AS builder
WORKDIR /app
COPY . .
RUN go build -o gorp-app ./cmd/app

FROM debian:stable-slim
WORKDIR /app
COPY --from=builder /app/gorp-app ./gorp-app
COPY config ./config
EXPOSE 8888
CMD ["./gorp-app", "app", "start"]
