//go:build !wireinject

// Code generated by Wire. DO NOT EDIT.

package main

import (
	"nop-go/services/content-service/internal/service"
	"gorm.io/gorm"
)

// wireContentServices Wire 生成的注入函数。
// 依赖链：gorm.DB -> service.NewServices -> *service.Services
func wireContentServices(db *gorm.DB) (*service.Services, error) {
	services := service.NewServices(db)
	return services, nil
}