// Code generated by Claude Code. DO NOT EDIT.

package main

import (
	"nop-go/services/import-service/internal/biz"
	"nop-go/services/import-service/internal/data"
	"nop-go/services/import-service/internal/service"
	"nop-go/shared/bootstrap"

	"github.com/ngq/gorp/framework/contract"
	"gorm.io/gorm"
)

func importConfigFromRuntime(rt *bootstrap.HTTPServiceRuntime) biz.ImportConfig {
	config := biz.ImportConfig{
		TempDir:                 rt.Config.GetString("import.temp_dir"),
		MaxFileSize:             int64(rt.Config.GetInt("import.max_file_size")),
		DefaultSeparator:        rt.Config.GetString("import.default_separator"),
		SkipAttributeValidation: rt.Config.GetBool("import.skip_attribute_validation"),
	}
	if config.TempDir == "" {
		config.TempDir = "./temp/import"
	}
	if config.MaxFileSize <= 0 {
		config.MaxFileSize = 50 * 1024 * 1024
	}
	if config.DefaultSeparator == "" {
		config.DefaultSeparator = ","
	}
	return config
}

func wireImportService(db *gorm.DB, jwtSvc contract.JWTService, config biz.ImportConfig) (*service.ImportService, error) {
	importProfileRepo := data.NewImportProfileRepository(db)
	exportProfileRepo := data.NewExportProfileRepository(db)
	importHistoryRepo := data.NewImportHistoryRepository(db)
	exportHistoryRepo := data.NewExportHistoryRepository(db)
	importErrorRepo := data.NewImportErrorRepository(db)
	importUC := biz.NewImportUseCase(importProfileRepo, importHistoryRepo, importErrorRepo, config)
	exportUC := biz.NewExportUseCase(exportProfileRepo, exportHistoryRepo, config)
	importService := service.NewImportService(importUC, exportUC, jwtSvc)
	return importService, nil
}
