# 商品服务镜像
FROM golang:1.22-alpine AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY proto/ ./proto/
COPY services/product/ ./services/product/
COPY services/user/ ./services/user/
COPY services/order/ ./services/order/
COPY pkg/ ./pkg/

RUN CGO_ENABLED=0 GOOS=linux go build -o /product ./services/product/cmd

FROM alpine:3.19

RUN apk add --no-cache ca-certificates tzdata

WORKDIR /app

COPY services/product/config/app.yaml ./config/app.yaml
COPY --from=builder /product .

EXPOSE 8083

ENTRYPOINT ["./product"]
