// Code generated by Claude Code. DO NOT EDIT.

package main

import (
	"nop-go/services/ai-service/internal/biz"
	"nop-go/services/ai-service/internal/data"
	"nop-go/services/ai-service/internal/service"
	"nop-go/shared/bootstrap"

	"github.com/ngq/gorp/framework/contract"
	"gorm.io/gorm"
)

func aiConfigFromRuntime(rt *bootstrap.HTTPServiceRuntime) biz.AIConfig {
	config := biz.AIConfig{
		Provider:    rt.Config.GetString("ai.provider"),
		APIKey:      rt.Config.GetString("ai.api_key"),
		APIEndpoint: rt.Config.GetString("ai.api_endpoint"),
		Model:       rt.Config.GetString("ai.model"),
		MaxTokens:   rt.Config.GetInt("ai.max_tokens"),
		Temperature: rt.Config.GetFloat("ai.temperature"),
		Timeout:     rt.Config.GetInt("ai.timeout"),
	}
	if config.Provider == "" {
		config.Provider = "openai"
	}
	if config.Model == "" {
		config.Model = "gpt-4"
	}
	if config.MaxTokens <= 0 {
		config.MaxTokens = 4096
	}
	if config.Temperature == 0 {
		config.Temperature = 0.7
	}
	if config.Timeout <= 0 {
		config.Timeout = 30
	}
	return config
}

func wireAIService(db *gorm.DB, jwtSvc contract.JWTService, config biz.AIConfig) (*service.AIService, error) {
	convRepo := data.NewAIConversationRepository(db)
	msgRepo := data.NewAIMessageRepository(db)
	recRepo := data.NewAIRecommendationRepository(db)
	sugRepo := data.NewAISearchSuggestionRepository(db)
	contentRepo := data.NewAIGeneratedContentRepository(db)
	modelRepo := data.NewAIModelConfigRepository(db)
	aiUC := biz.NewAIUseCase(convRepo, msgRepo, recRepo, sugRepo, contentRepo, modelRepo, config)
	modelUC := biz.NewAIModelConfigUseCase(modelRepo)
	aiService := service.NewAIService(aiUC, modelUC, jwtSvc)
	return aiService, nil
}
