//go:build !wireinject

// Code generated by Wire. DO NOT EDIT.

package main

import (
	"nop-go/services/tax/internal/service"

	"gorm.io/gorm"
)

// wireTaxServices 通过 Wire 注入数据库连接，构建税务服务实例
func wireTaxServices(db *gorm.DB) (*service.TaxService, error) {
	svc := service.NewTaxService(db)
	return svc, nil
}
