apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nop-go-dev

resources:
  - ../../base

images:
  - name: your-registry/nop-go-user-service
    newName: nop-go-user-service
    newTag: dev
  - name: your-registry/nop-go-order-service
    newName: nop-go-order-service
    newTag: dev
  - name: your-registry/nop-go-product-service
    newName: nop-go-product-service
    newTag: dev

patches:
  - path: deployment-patch.yaml
