//go:build !wireinject

// Code generated by Wire. DO NOT EDIT.

package main

import (
	"nop-go/services/trade-service/internal/service"
	"gorm.io/gorm"
)

// wireTradeServices 通过 Wire 注入数据库连接，构建交易服务容器
func wireTradeServices(db *gorm.DB) (*service.Services, error) {
	services := service.NewServices(db)
	return services, nil
}