//go:build !wireinject

// Code generated by Wire. DO NOT EDIT.

package main

import (
	"nop-go/services/shipping/internal/service"
	"gorm.io/gorm"
)

func wireShippingServices(db *gorm.DB) (*service.ShippingService, error) {
	services := service.NewShippingService(db)
	return services, nil
}
