// Code generated by Claude Code. DO NOT EDIT.

package main

import (
	"nop-go/services/order-service/internal/biz"
	"nop-go/services/order-service/internal/data"
	"nop-go/services/order-service/internal/service"

	"gorm.io/gorm"
)

func wireOrderService(db *gorm.DB) (*service.OrderService, error) {
	orderRepo := data.NewOrderRepository(db)
	orderItemRepo := data.NewOrderItemRepository(db)
	addressRepo := data.NewOrderAddressRepository(db)
	giftCardRepo := data.NewGiftCardRepository(db)
	returnRepo := data.NewReturnRequestRepository(db)
	orderUC := biz.NewOrderUseCase(orderRepo, orderItemRepo, addressRepo, giftCardRepo, returnRepo)
	giftCardUC := biz.NewGiftCardUseCase(giftCardRepo)
	returnUC := biz.NewReturnRequestUseCase(returnRepo, orderRepo)
	orderService := service.NewOrderService(orderUC, giftCardUC, returnUC)
	return orderService, nil
}
