//go:build !wireinject

// Code generated by Wire. DO NOT EDIT.

package main

import (
	"nop-go/services/discount/internal/service"

	"gorm.io/gorm"
)

// wireDiscountServices 通过 Wire 注入数据库连接，构建折扣服务实例
func wireDiscountServices(db *gorm.DB) (*service.DiscountService, error) {
	svc := service.NewDiscountService(db)
	return svc, nil
}
