#!/usr/bin/env bash
set -euo pipefail

go test -race ./framework/container/...
go test -race ./framework/contract/...
go test -race ./framework/provider/...
go test -race ./framework/bootstrap/...
go test -race ./contrib/...
go test ./cmd/gorp/cmd -run "Bootstrap|Template|OfflineAndRelease|Diff|Upgrade|Pack|MultiFlatWire|MultiIndependent|RootCommand|PublicStarterMatrix|Repo(Role|Asset)|APIArtifact|Proto|GeneratedArtifact|DocGen|DocDist"
kubectl kustomize deploy/kubernetes/overlays/dev >/dev/null
kubectl kustomize deploy/kubernetes/overlays/staging >/dev/null
kubectl kustomize deploy/kubernetes/overlays/prod >/dev/null
