//go:build !wireinject

// Code generated by Wire. DO NOT EDIT.

package main

import (
	"nop-go/services/catalog-service/internal/service"
	"gorm.io/gorm"
)

// wireCatalogServices 手动依赖注入（wire_gen 产物）。
// 合并 product + directory + media + seo 四个服务。
func wireCatalogServices(db *gorm.DB) (*service.Services, error) {
	services := service.NewServices(db)
	return services, nil
}
