// Code generated by Claude Code. DO NOT EDIT.

package main

import (
	"nop-go/services/catalog-service/internal/biz"
	"nop-go/services/catalog-service/internal/data"
	"nop-go/services/catalog-service/internal/service"

	"gorm.io/gorm"
)

// wireCatalogService 使用接近 multi-flat-wire 的方式收口 catalog-service 的装配链。
func wireCatalogService(db *gorm.DB) (*service.CatalogService, error) {
	productRepo := data.NewProductRepository(db)
	categoryRepo := data.NewCategoryRepository(db)
	manufacturerRepo := data.NewManufacturerRepository(db)
	pictureRepo := data.NewProductPictureRepository(db)
	reviewRepo := data.NewProductReviewRepository(db)

	productUC := biz.NewProductUseCase(productRepo, categoryRepo, manufacturerRepo, pictureRepo)
	categoryUC := biz.NewCategoryUseCase(categoryRepo)
	manufacturerUC := biz.NewManufacturerUseCase(manufacturerRepo)
	pictureUC := biz.NewProductPictureUseCase(pictureRepo, productRepo)
	reviewUC := biz.NewProductReviewUseCase(reviewRepo, productRepo)

	catalogService := service.NewCatalogService(productUC, categoryUC, manufacturerUC, pictureUC, reviewUC, service.Options{
		EnableMedia:  true,
		EnableReview: true,
	})
	return catalogService, nil
}
