// Code generated by Claude Code. DO NOT EDIT.

package main

import (
	"nop-go/services/shipping-service/internal/biz"
	"nop-go/services/shipping-service/internal/data"
	"nop-go/services/shipping-service/internal/service"

	"gorm.io/gorm"
)

func wireShippingService(db *gorm.DB) (*service.ShippingService, error) {
	shipmentRepo := data.NewShipmentRepository(db)
	shipmentItemRepo := data.NewShipmentItemRepository(db)
	methodRepo := data.NewShippingMethodRepository(db)
	trackingRepo := data.NewShipmentTrackingRepository(db)
	shipmentUC := biz.NewShipmentUseCase(shipmentRepo, shipmentItemRepo, methodRepo, trackingRepo)
	methodUC := biz.NewShippingMethodUseCase(methodRepo)
	shippingService := service.NewShippingService(shipmentUC, methodUC)
	return shippingService, nil
}
