// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/user/v1/user.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetUserReq 获取用户请求
type GetUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReq) Reset() {
	*x = GetUserReq{}
	mi := &file_api_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReq) ProtoMessage() {}

func (x *GetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReq.ProtoReflect.Descriptor instead.
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetUserResp 获取用户响应
type GetUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                               // 用户ID
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`                    // 用户名
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`                          // 邮箱
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`                          // 手机号
	Nickname      string                 `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`                    // 昵称
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`                        // 头像URL
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`                       // 状态
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 创建时间
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResp) Reset() {
	*x = GetUserResp{}
	mi := &file_api_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResp) ProtoMessage() {}

func (x *GetUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResp.ProtoReflect.Descriptor instead.
func (*GetUserResp) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserResp) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetUserResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserResp) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetUserResp) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetUserResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetUserResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetUserResp) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetUserResp) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// ListUserAddressesReq 获取用户地址列表请求
type ListUserAddressesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserAddressesReq) Reset() {
	*x = ListUserAddressesReq{}
	mi := &file_api_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserAddressesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserAddressesReq) ProtoMessage() {}

func (x *ListUserAddressesReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserAddressesReq.ProtoReflect.Descriptor instead.
func (*ListUserAddressesReq) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *ListUserAddressesReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// ListUserAddressesResp 获取用户地址列表响应
type ListUserAddressesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AddressItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // 地址列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserAddressesResp) Reset() {
	*x = ListUserAddressesResp{}
	mi := &file_api_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserAddressesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserAddressesResp) ProtoMessage() {}

func (x *ListUserAddressesResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserAddressesResp.ProtoReflect.Descriptor instead.
func (*ListUserAddressesResp) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *ListUserAddressesResp) GetItems() []*AddressItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// AddressItem 地址条目
type AddressItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                           // 地址ID
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                     // 用户ID
	RecipientName string                 `protobuf:"bytes,3,opt,name=recipient_name,json=recipientName,proto3" json:"recipient_name,omitempty"` // 收件人姓名
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`                                      // 收件人电话
	Province      string                 `protobuf:"bytes,5,opt,name=province,proto3" json:"province,omitempty"`                                // 省份
	City          string                 `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`                                        // 城市
	District      string                 `protobuf:"bytes,7,opt,name=district,proto3" json:"district,omitempty"`                                // 区县
	Detail        string                 `protobuf:"bytes,8,opt,name=detail,proto3" json:"detail,omitempty"`                                    // 详细地址
	IsDefault     bool                   `protobuf:"varint,9,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`            // 是否默认地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressItem) Reset() {
	*x = AddressItem{}
	mi := &file_api_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressItem) ProtoMessage() {}

func (x *AddressItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressItem.ProtoReflect.Descriptor instead.
func (*AddressItem) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *AddressItem) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddressItem) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddressItem) GetRecipientName() string {
	if x != nil {
		return x.RecipientName
	}
	return ""
}

func (x *AddressItem) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AddressItem) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *AddressItem) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AddressItem) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *AddressItem) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *AddressItem) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

var File_api_user_v1_user_proto protoreflect.FileDescriptor

const file_api_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x16api/user/v1/user.proto\x12\auser.v1\"\x1c\n" +
	"\n" +
	"GetUserReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\xef\x01\n" +
	"\vGetUserResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1a\n" +
	"\bnickname\x18\x05 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"/\n" +
	"\x14ListUserAddressesReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"C\n" +
	"\x15ListUserAddressesResp\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.user.v1.AddressItemR\x05items\"\xf6\x01\n" +
	"\vAddressItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12%\n" +
	"\x0erecipient_name\x18\x03 \x01(\tR\rrecipientName\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1a\n" +
	"\bprovince\x18\x05 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x06 \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\a \x01(\tR\bdistrict\x12\x16\n" +
	"\x06detail\x18\b \x01(\tR\x06detail\x12\x1d\n" +
	"\n" +
	"is_default\x18\t \x01(\bR\tisDefault2\x93\x01\n" +
	"\aUserRPC\x124\n" +
	"\aGetUser\x12\x13.user.v1.GetUserReq\x1a\x14.user.v1.GetUserResp\x12R\n" +
	"\x11ListUserAddresses\x12\x1d.user.v1.ListUserAddressesReq\x1a\x1e.user.v1.ListUserAddressesRespB1Z/nop-go/services/user-service/api/user/v1;userv1b\x06proto3"

var (
	file_api_user_v1_user_proto_rawDescOnce sync.Once
	file_api_user_v1_user_proto_rawDescData []byte
)

func file_api_user_v1_user_proto_rawDescGZIP() []byte {
	file_api_user_v1_user_proto_rawDescOnce.Do(func() {
		file_api_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_user_v1_user_proto_rawDesc), len(file_api_user_v1_user_proto_rawDesc)))
	})
	return file_api_user_v1_user_proto_rawDescData
}

var file_api_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_user_v1_user_proto_goTypes = []any{
	(*GetUserReq)(nil),            // 0: user.v1.GetUserReq
	(*GetUserResp)(nil),           // 1: user.v1.GetUserResp
	(*ListUserAddressesReq)(nil),  // 2: user.v1.ListUserAddressesReq
	(*ListUserAddressesResp)(nil), // 3: user.v1.ListUserAddressesResp
	(*AddressItem)(nil),           // 4: user.v1.AddressItem
}
var file_api_user_v1_user_proto_depIdxs = []int32{
	4, // 0: user.v1.ListUserAddressesResp.items:type_name -> user.v1.AddressItem
	0, // 1: user.v1.UserRPC.GetUser:input_type -> user.v1.GetUserReq
	2, // 2: user.v1.UserRPC.ListUserAddresses:input_type -> user.v1.ListUserAddressesReq
	1, // 3: user.v1.UserRPC.GetUser:output_type -> user.v1.GetUserResp
	3, // 4: user.v1.UserRPC.ListUserAddresses:output_type -> user.v1.ListUserAddressesResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_user_v1_user_proto_init() }
func file_api_user_v1_user_proto_init() {
	if File_api_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_v1_user_proto_rawDesc), len(file_api_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_user_v1_user_proto_goTypes,
		DependencyIndexes: file_api_user_v1_user_proto_depIdxs,
		MessageInfos:      file_api_user_v1_user_proto_msgTypes,
	}.Build()
	File_api_user_v1_user_proto = out.File
	file_api_user_v1_user_proto_goTypes = nil
	file_api_user_v1_user_proto_depIdxs = nil
}
