// Code generated by Claude Code. DO NOT EDIT.

package main

import (
	"nop-go/services/cart-service/internal/biz"
	"nop-go/services/cart-service/internal/data"
	"nop-go/services/cart-service/internal/service"

	"github.com/ngq/gorp/framework/contract"
	"gorm.io/gorm"
)

func wireCartService(db *gorm.DB, jwtSvc contract.JWTService) (*service.CartService, error) {
	cartRepo := data.NewShoppingCartRepository(db)
	cartItemRepo := data.NewCartItemRepository(db)
	wishlistRepo := data.NewWishlistRepository(db)
	wishlistItemRepo := data.NewWishlistItemRepository(db)
	cartUC := biz.NewCartUseCase(cartRepo, cartItemRepo)
	wishlistUC := biz.NewWishlistUseCase(wishlistRepo, wishlistItemRepo)
	cartService := service.NewCartService(cartUC, wishlistUC, jwtSvc)
	return cartService, nil
}
