// Code generated by Claude Code. DO NOT EDIT.

package main

import (
	"nop-go/services/localization-service/internal/biz"
	"nop-go/services/localization-service/internal/data"
	"nop-go/services/localization-service/internal/service"

	securitycontract "github.com/ngq/gorp/framework/contract/security"
	"gorm.io/gorm"
)

// wireLocalizationService 浣跨敤鎺ヨ繎 multi-flat-wire 鐨勬柟寮忔敹鍙?localization-service 鐨勮閰嶉摼銆?
func wireLocalizationService(db *gorm.DB, jwtSvc securitycontract.JWTService) (*service.LocalizationService, error) {
	languageRepo := data.NewLanguageRepository(db)
	resourceRepo := data.NewLocaleStringResourceRepository(db)
	currencyRepo := data.NewCurrencyRepository(db)

	locUC := biz.NewLocalizationUseCase(languageRepo, resourceRepo, currencyRepo)
	locService := service.NewLocalizationService(locUC, jwtSvc)
	return locService, nil
}
