// Code generated by Claude Code. DO NOT EDIT.

package main

import (
	"nop-go/services/localization-service/internal/biz"
	"nop-go/services/localization-service/internal/data"
	"nop-go/services/localization-service/internal/service"

	"github.com/ngq/gorp/framework/contract"
	"gorm.io/gorm"
)

// wireLocalizationService 使用接近 multi-flat-wire 的方式收口 localization-service 的装配链。
func wireLocalizationService(db *gorm.DB, jwtSvc contract.JWTService) (*service.LocalizationService, error) {
	languageRepo := data.NewLanguageRepository(db)
	resourceRepo := data.NewLocaleStringResourceRepository(db)
	currencyRepo := data.NewCurrencyRepository(db)

	locUC := biz.NewLocalizationUseCase(languageRepo, resourceRepo, currencyRepo)
	locService := service.NewLocalizationService(locUC, jwtSvc)
	return locService, nil
}
