// Code generated by Claude Code. DO NOT EDIT.

package main

import (
	"nop-go/services/store-service/internal/biz"
	"nop-go/services/store-service/internal/data"
	"nop-go/services/store-service/internal/service"

	securitycontract "github.com/ngq/gorp/framework/contract/security"
	"gorm.io/gorm"
)

// wireStoreService 浣跨敤鎺ヨ繎 multi-flat-wire 鐨勬柟寮忔敹鍙?store-service 鐨勮閰嶉摼銆?
func wireStoreService(db *gorm.DB, jwtSvc securitycontract.JWTService) (*service.StoreService, error) {
	storeRepo := data.NewStoreRepository(db)
	vendorRepo := data.NewVendorRepository(db)
	svRepo := data.NewStoreVendorRepository(db)
	noteRepo := data.NewVendorNoteRepository(db)

	storeUC := biz.NewStoreUseCase(storeRepo, vendorRepo, svRepo)
	vendorUC := biz.NewVendorUseCase(vendorRepo, storeRepo, svRepo, noteRepo)
	storeService := service.NewStoreService(storeUC, vendorUC, jwtSvc)
	return storeService, nil
}
