// Code generated by Claude Code. DO NOT EDIT.

package main

import (
	"nop-go/services/store-service/internal/biz"
	"nop-go/services/store-service/internal/data"
	"nop-go/services/store-service/internal/service"

	"github.com/ngq/gorp/framework/contract"
	"gorm.io/gorm"
)

// wireStoreService 使用接近 multi-flat-wire 的方式收口 store-service 的装配链。
func wireStoreService(db *gorm.DB, jwtSvc contract.JWTService) (*service.StoreService, error) {
	storeRepo := data.NewStoreRepository(db)
	vendorRepo := data.NewVendorRepository(db)
	svRepo := data.NewStoreVendorRepository(db)
	noteRepo := data.NewVendorNoteRepository(db)

	storeUC := biz.NewStoreUseCase(storeRepo, vendorRepo, svRepo)
	vendorUC := biz.NewVendorUseCase(vendorRepo, storeRepo, svRepo, noteRepo)
	storeService := service.NewStoreService(storeUC, vendorUC, jwtSvc)
	return storeService, nil
}
